# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'Filter',
    'FilterContext',
    'FilterPlanner',
    'FilterPrimitiveDescriptor',
    'FilterRegistry',
    'FilterRenderer',
    'FilterResult',
    'ResolvedFilter',
    'build_filter_element',
    'build_filter_node',
    'resolve_filter_element',
    'resolve_filter_node',
    'resolve_filter_reference',
    'base',
    'effects',
    'image',
    'planner',
    'primitives',
    'registry',
    'renderer',
    'resvg_bridge',
    'utils'
]

# map symbol -> relative module
_symbol_map = {'Filter': 'base', 'FilterContext': 'base', 'FilterResult': 'base', 'FilterPlanner': 'planner', 'FilterRegistry': 'registry', 'FilterRenderer': 'renderer', 'ResolvedFilter': 'resvg_bridge', 'resolve_filter_node': 'resvg_bridge', 'FilterPrimitiveDescriptor': 'resvg_bridge', 'build_filter_node': 'resvg_bridge', 'resolve_filter_reference': 'resvg_bridge', 'resolve_filter_element': 'resvg_bridge', 'build_filter_element': 'resvg_bridge'}
_module_map = {'base': 'base', 'effects': 'effects', 'image': 'image', 'planner': 'planner', 'primitives': 'primitives', 'registry': 'registry', 'renderer': 'renderer', 'resvg_bridge': 'resvg_bridge', 'utils': 'utils'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
