# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'BasicSmartFontConverter',
    'ClipAnalysis',
    'ColorNormalizedImage',
    'ColorSpaceService',
    'ConversionServices',
    'ConverterCache',
    'FilterEffectResult',
    'FilterService',
    'GradientAnalysis',
    'GradientComplexity',
    'GradientMetrics',
    'GradientOptimisation',
    'GradientOptimisationPlan',
    'GradientProcessor',
    'GradientService',
    'ImageResource',
    'ImageService',
    'MarkerService',
    'MaskComputeResult',
    'PatternService',
    'Resolver',
    'SmartFontConverter',
    'StructuredClipService',
    'StructuredMaskService',
    'SymbolService',
    'build_smart_font_converter',
    'configure_services',
    'cache',
    'clip_service',
    'color_service',
    'conversion',
    'filter_service',
    'filter_types',
    'font_converter',
    'fonts',
    'fonts.providers',
    'gradient_processor',
    'gradient_service',
    'image_service',
    'marker_service',
    'mask_service',
    'pattern_service',
    'providers',
    'registry',
    'setup',
    'symbol_service'
]

# map symbol -> relative module
_symbol_map = {'ConverterCache': 'cache', 'StructuredClipService': 'clip_service', 'ClipAnalysis': 'clip_service', 'ColorNormalizedImage': 'color_service', 'ColorSpaceService': 'color_service', 'ConversionServices': 'conversion', 'FilterService': 'filter_service', 'FilterEffectResult': 'filter_types', 'SmartFontConverter': 'font_converter', 'BasicSmartFontConverter': 'font_converter', 'build_smart_font_converter': 'font_converter', 'GradientComplexity': 'gradient_processor', 'GradientAnalysis': 'gradient_processor', 'GradientProcessor': 'gradient_processor', 'GradientOptimisationPlan': 'gradient_processor', 'GradientOptimisation': 'gradient_processor', 'GradientMetrics': 'gradient_processor', 'GradientService': 'gradient_service', 'ImageService': 'image_service', 'ImageResource': 'image_service', 'Resolver': 'image_service', 'MarkerService': 'marker_service', 'MaskComputeResult': 'mask_service', 'StructuredMaskService': 'mask_service', 'PatternService': 'pattern_service', 'configure_services': 'setup', 'SymbolService': 'symbol_service'}
_module_map = {'cache': 'cache', 'clip_service': 'clip_service', 'color_service': 'color_service', 'conversion': 'conversion', 'filter_service': 'filter_service', 'filter_types': 'filter_types', 'font_converter': 'font_converter', 'fonts': 'fonts', 'fonts.providers': 'fonts.providers', 'gradient_processor': 'gradient_processor', 'gradient_service': 'gradient_service', 'image_service': 'image_service', 'marker_service': 'marker_service', 'mask_service': 'mask_service', 'pattern_service': 'pattern_service', 'providers': 'providers', 'registry': 'registry', 'setup': 'setup', 'symbol_service': 'symbol_service'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
