# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'PPTConverter',
    'PPT_ANGLE_SCALE',
    'PPT_OPACITY_SCALE',
    'PPT_SCALE',
    'alpha_to_ppt',
    'degrees_to_ppt',
    'hex_to_rgb',
    'opacity_to_ppt',
    'parse_angle',
    'parse_color',
    'parse_numeric_list',
    'parse_scale_pair',
    'parse_translation_pair',
    'percentage_to_ppt',
    'position_to_ppt',
    'ppt_to_alpha',
    'ppt_to_degrees',
    'ppt_to_opacity',
    'ppt_to_percentage',
    'ppt_to_radians',
    'radians_to_ppt',
    'rgb_to_hex',
    'scale_to_ppt',
    'angles',
    'colors',
    'opacity',
    'powerpoint',
    'scale',
    'transforms',
    'units'
]

# map symbol -> relative module
_symbol_map = {'ppt_to_degrees': 'angles', 'radians_to_ppt': 'angles', 'ppt_to_radians': 'angles', 'degrees_to_ppt': 'angles', 'PPT_ANGLE_SCALE': 'angles', 'rgb_to_hex': 'colors', 'hex_to_rgb': 'colors', 'parse_color': 'colors', 'alpha_to_ppt': 'opacity', 'ppt_to_opacity': 'opacity', 'PPT_OPACITY_SCALE': 'opacity', 'ppt_to_percentage': 'opacity', 'percentage_to_ppt': 'opacity', 'ppt_to_alpha': 'opacity', 'opacity_to_ppt': 'opacity', 'PPTConverter': 'powerpoint', 'scale_to_ppt': 'scale', 'position_to_ppt': 'scale', 'PPT_SCALE': 'scale', 'parse_scale_pair': 'transforms', 'parse_angle': 'transforms', 'parse_numeric_list': 'transforms', 'parse_translation_pair': 'transforms'}
_module_map = {'angles': 'angles', 'colors': 'colors', 'opacity': 'opacity', 'powerpoint': 'powerpoint', 'scale': 'scale', 'transforms': 'transforms', 'units': 'units'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
