# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

_missing_dependencies: list[str] = []
_core_import_error: BaseException | None = None
_AdvancedColorImpl = None

try:  # pragma: no cover - optional dependency probe
    import numpy as _np  # type: ignore
except Exception:
    _missing_dependencies.append("numpy")
else:  # pragma: no cover - cleanup when available
    del _np

try:  # pragma: no cover - optional dependency probe
    import colorspacious as _colorspacious  # type: ignore
except Exception:
    _missing_dependencies.append("colorspacious")
else:  # pragma: no cover - cleanup when available
    del _colorspacious

if not _missing_dependencies:
    try:
        from .core import Color as _AdvancedColorImpl  # type: ignore
    except Exception as exc:  # pragma: no cover - surfaced through require_color_engine
        _core_import_error = exc

COLOR_ENGINE_AVAILABLE = bool(_AdvancedColorImpl)


def require_color_engine() -> None:
    """Raise a helpful error when the advanced colour engine cannot be used."""

    if COLOR_ENGINE_AVAILABLE:
        return

    details: list[str] = []
    if _missing_dependencies:
        details.append(f"missing dependencies: {', '.join(sorted(set(_missing_dependencies)))}")
    if _core_import_error is not None:
        details.append(f"core import failed: {_core_import_error}")
    hint = "Install the optional colour extras (numpy, colorspacious) to enable advanced colour features."
    if details:
        message = f"Advanced colour engine unavailable ({'; '.join(details)}). {hint}"
    else:
        message = f"Advanced colour engine unavailable. {hint}"
    raise RuntimeError(message)


if COLOR_ENGINE_AVAILABLE and _AdvancedColorImpl is not None:
    AdvancedColor = _AdvancedColorImpl
else:

    class AdvancedColor:  # type: ignore[override]
        """Fallback stub that surfaces helpful guidance when dependencies are missing."""

        def __init__(self, *args, **kwargs) -> None:
            require_color_engine()

        def __getattr__(self, _name: str) -> _Any:  # pragma: no cover - unreachable, but defensive
            require_color_engine()


__all__ = [
    'AdvancedColor',
    'BlendMode',
    'COLOR_ENGINE_AVAILABLE',
    'CSS_NAMED_COLORS',
    'Color',
    'ColorAccessibility',
    'ColorBatch',
    'ColorBlindnessType',
    'ColorHarmony',
    'ColorManipulation',
    'ColorParser',
    'ColorSpaceConverter',
    'ContrastLevel',
    'NAMED_COLORS',
    'color_to_hex',
    'get_css_color',
    'is_css_color',
    'oklab_to_oklch',
    'oklab_to_rgb',
    'oklch_to_oklab',
    'oklch_to_rgb',
    'require_color_engine',
    'rgb_to_oklab',
    'rgb_to_oklch',
    'accessibility',
    'batch',
    'color_spaces',
    'core',
    'css_colors',
    'harmony',
    'manipulation',
    'parser',
    'utils'
]

# map symbol -> relative module
_symbol_map = {'ColorBlindnessType': 'accessibility', 'ContrastLevel': 'accessibility', 'ColorAccessibility': 'accessibility', 'ColorBatch': 'batch', 'oklch_to_oklab': 'color_spaces', 'rgb_to_oklch': 'color_spaces', 'oklab_to_oklch': 'color_spaces', 'oklab_to_rgb': 'color_spaces', 'oklch_to_rgb': 'color_spaces', 'ColorSpaceConverter': 'color_spaces', 'rgb_to_oklab': 'color_spaces', 'Color': 'core', 'get_css_color': 'css_colors', 'CSS_NAMED_COLORS': 'css_colors', 'NAMED_COLORS': 'css_colors', 'is_css_color': 'css_colors', 'ColorHarmony': 'harmony', 'ColorManipulation': 'manipulation', 'BlendMode': 'manipulation', 'ColorParser': 'parser', 'color_to_hex': 'utils'}
_module_map = {'accessibility': 'accessibility', 'batch': 'batch', 'color_spaces': 'color_spaces', 'core': 'core', 'css_colors': 'css_colors', 'harmony': 'harmony', 'manipulation': 'manipulation', 'parser': 'parser', 'utils': 'utils'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
