# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'StyleExtractor',
    'StyleResult',
    'apply_use_attributes',
    'apply_use_transform',
    'compute_use_transform',
    'extract_style',
    'instantiate_use_target',
    'matrix_to_string',
    'prepend_transform',
    'propagate_symbol_use_attributes',
    'resolve_use_offsets',
    'wrap_symbol_clone',
    'style_extractor',
    'style_runtime',
    'use_expander'
]

# map symbol -> relative module
_symbol_map = {'StyleExtractor': 'style_extractor', 'StyleResult': 'style_extractor', 'extract_style': 'style_runtime', 'instantiate_use_target': 'use_expander', 'prepend_transform': 'use_expander', 'apply_use_attributes': 'use_expander', 'wrap_symbol_clone': 'use_expander', 'propagate_symbol_use_attributes': 'use_expander', 'resolve_use_offsets': 'use_expander', 'apply_use_transform': 'use_expander', 'compute_use_transform': 'use_expander', 'matrix_to_string': 'use_expander'}
_module_map = {'style_extractor': 'style_extractor', 'style_runtime': 'style_runtime', 'use_expander': 'use_expander'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
