# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'BookmarkTarget',
    'ConversionPipeline',
    'CustomShowTarget',
    'NavigationAction',
    'NavigationKind',
    'NavigationSpec',
    'SlideTarget',
    'parse_svg_navigation',
    'mappers',
    'navigation',
    'pipeline'
]

# map symbol -> relative module
_symbol_map = {'NavigationSpec': 'navigation', 'NavigationKind': 'navigation', 'SlideTarget': 'navigation', 'parse_svg_navigation': 'navigation', 'CustomShowTarget': 'navigation', 'BookmarkTarget': 'navigation', 'NavigationAction': 'navigation', 'ConversionPipeline': 'pipeline'}
_module_map = {'mappers': 'mappers', 'navigation': 'navigation', 'pipeline': 'pipeline'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
