# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'BaseNode',
    'CircleNode',
    'ClipPathNode',
    'Config',
    'DEFAULT_CONFIG',
    'EllipseNode',
    'FeatureFlag',
    'FilterNode',
    'FilterPrimitive',
    'GenericNode',
    'GroupNode',
    'ImageNode',
    'LineNode',
    'LinearGradientNode',
    'MarkerNode',
    'MaskNode',
    'NormalizationError',
    'NormalizationResult',
    'PaintServerNode',
    'PathNode',
    'PatternNode',
    'PolyNode',
    'RadialGradientNode',
    'RectNode',
    'SVG_NAMESPACE',
    'TextNode',
    'TextSpan',
    'Tree',
    'UseNode',
    'build_tree',
    'load_config',
    'normalize_svg_bytes',
    'normalize_svg_element',
    'normalize_svg_file',
    'normalize_svg_string',
    'config',
    'constants',
    'geometry',
    'normalizer',
    'painting',
    'parser',
    'text',
    'usvg_tree',
    'utils'
]

# map symbol -> relative module
_symbol_map = {'Config': 'config', 'load_config': 'config', 'DEFAULT_CONFIG': 'config', 'FeatureFlag': 'constants', 'normalize_svg_bytes': 'normalizer', 'normalize_svg_file': 'normalizer', 'NormalizationError': 'normalizer', 'NormalizationResult': 'normalizer', 'normalize_svg_string': 'normalizer', 'normalize_svg_element': 'normalizer', 'PathNode': 'usvg_tree', 'CircleNode': 'usvg_tree', 'BaseNode': 'usvg_tree', 'LineNode': 'usvg_tree', 'GenericNode': 'usvg_tree', 'MarkerNode': 'usvg_tree', 'FilterNode': 'usvg_tree', 'Tree': 'usvg_tree', 'ImageNode': 'usvg_tree', 'ClipPathNode': 'usvg_tree', 'UseNode': 'usvg_tree', 'PatternNode': 'usvg_tree', 'FilterPrimitive': 'usvg_tree', 'GroupNode': 'usvg_tree', 'TextSpan': 'usvg_tree', 'SVG_NAMESPACE': 'usvg_tree', 'PaintServerNode': 'usvg_tree', 'LinearGradientNode': 'usvg_tree', 'build_tree': 'usvg_tree', 'EllipseNode': 'usvg_tree', 'PolyNode': 'usvg_tree', 'TextNode': 'usvg_tree', 'RectNode': 'usvg_tree', 'MaskNode': 'usvg_tree', 'RadialGradientNode': 'usvg_tree'}
_module_map = {'config': 'config', 'constants': 'constants', 'geometry': 'geometry', 'normalizer': 'normalizer', 'painting': 'painting', 'parser': 'parser', 'text': 'text', 'usvg_tree': 'usvg_tree', 'utils': 'utils'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
