"""Simplified usvg::Tree representation with typed nodes."""

from __future__ import annotations

from .usvg_nodes import (
    BaseNode,
    CircleNode,
    ClipPathNode,
    EllipseNode,
    FilterNode,
    FilterPrimitive,
    GenericNode,
    GroupNode,
    ImageNode,
    LinearGradientNode,
    LineNode,
    MarkerNode,
    MaskNode,
    PaintServer,
    PaintServerNode,
    PathNode,
    PatternNode,
    PolyNode,
    RadialGradientNode,
    RectNode,
    TextNode,
    TextSpan,
    Tree,
    UseNode,
)
from .usvg_tree_builder import build_tree
from .usvg_tree_utils import SVG_NAMESPACE

__all__ = [
    "BaseNode",
    "CircleNode",
    "ClipPathNode",
    "EllipseNode",
    "FilterNode",
    "FilterPrimitive",
    "GenericNode",
    "GroupNode",
    "ImageNode",
    "LineNode",
    "LinearGradientNode",
    "MarkerNode",
    "MaskNode",
    "PaintServer",
    "PaintServerNode",
    "PathNode",
    "PatternNode",
    "PolyNode",
    "RadialGradientNode",
    "RectNode",
    "SVG_NAMESPACE",
    "TextNode",
    "TextSpan",
    "Tree",
    "UseNode",
    "build_tree",
]
