steps:
  # Deploy to Firebase Hosting using official Firebase CLI image
  - name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
    args: ['deploy', '--project=powerful-layout-467812-p1', '--only=hosting']

timeout: 600s
