# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'AnimationPolicy',
    'AnimationXMLBuilder',
    'DrawingMLAnimationWriter',
    'TAVBuilder',
    'ValueFormatter',
    'ValueProcessor',
    'format_angle_value',
    'format_color_value',
    'format_numeric_value',
    'format_point_value',
    'constants',
    'handlers',
    'policy',
    'tav_builder',
    'value_formatters',
    'value_processors',
    'writer',
    'xml_builders'
]

# map symbol -> relative module
_symbol_map = {'AnimationPolicy': 'policy', 'ValueFormatter': 'tav_builder', 'TAVBuilder': 'tav_builder', 'format_angle_value': 'value_formatters', 'format_color_value': 'value_formatters', 'format_numeric_value': 'value_formatters', 'format_point_value': 'value_formatters', 'ValueProcessor': 'value_processors', 'DrawingMLAnimationWriter': 'writer', 'AnimationXMLBuilder': 'xml_builders'}
_module_map = {'constants': 'constants', 'handlers': 'handlers', 'policy': 'policy', 'tav_builder': 'tav_builder', 'value_formatters': 'value_formatters', 'value_processors': 'value_processors', 'writer': 'writer', 'xml_builders': 'xml_builders'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
