"""Animation oracle template loader.

Loads the parameterised ``<p:par>`` fragment templates from
``src/svg2ooxml/assets/animation_oracle/`` and substitutes the runtime tokens
each handler needs to specialise a preset for a particular shape.

The oracle is the single source of truth for the XML shape svg2ooxml emits
per PowerPoint animation preset. Handlers should load a slot by name rather
than constructing ``<p:par>`` trees imperatively.

This module also exposes three structured XML SSOT files that describe the
PowerPoint animation vocabulary:

- ``filter_vocabulary.xml`` — the 29-entry ``<p:animEffect filter>`` catalog
  (loaded via :meth:`AnimationOracle.filter_vocabulary`)
- ``attrname_vocabulary.xml`` — the 17 valid ``<p:attrName>`` values
  (loaded via :meth:`AnimationOracle.attrname_vocabulary`)
- ``dead_paths.xml`` — empirically falsified shapes that PPT silently drops
  (loaded via :meth:`AnimationOracle.dead_paths`)

The companion **pptx-animation skill** at ``.claude/skills/pptx-animation/``
(generated by ``tools/build_skill.py``) packages the oracle + these SSOT
files into a Claude-invocable skill with CLI scripts for emitting
entrance, exit, emphasis compound, and motion-path effects, plus a
validator that checks arbitrary XML against ``dead_paths.xml``.

Example::

    oracle = AnimationOracle()
    par = oracle.instantiate(
        "entr/fade",
        shape_id="2",
        par_id=6,
        duration_ms=1500,
        delay_ms=0,
        set_behavior_id=7,
        effect_behavior_id=71,
    )
    # ``par`` is an ``lxml`` element ready to be appended to the timing tree.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

from lxml import etree

from svg2ooxml.drawingml.animation.constants import SVG2_ANIMATION_NS
from svg2ooxml.drawingml.animation.evidence import (
    EvidenceTier,
    evidence_tiers_for_oracle_verification,
)
from svg2ooxml.drawingml.xml_builder import NS_P

NS_A = "http://schemas.openxmlformats.org/drawingml/2006/main"
_BUILD_MODE_ATTR = f"{{{SVG2_ANIMATION_NS}}}bldMode"

__all__ = [
    "AnimationOracle",
    "AttrNameEntry",
    "BehaviorFragment",
    "DeadPath",
    "EvidenceTier",
    "FilterEntry",
    "OracleSlotError",
    "PresetSlot",
    "default_oracle",
]


class OracleSlotError(KeyError):
    """Raised when a requested oracle slot cannot be resolved."""


@dataclass(frozen=True, slots=True)
class PresetSlot:
    """Metadata describing a single oracle slot."""

    name: str
    path: Path
    preset_class: str
    preset_id: int | None
    preset_subtype: int | None
    bld_mode: str
    family_signature: str
    content_tokens: tuple[str, ...]
    behavior_tokens: tuple[str, ...]
    smil_patterns: tuple[str, ...]
    source: str
    verification: str
    notes: str = ""

    @property
    def evidence_tiers(self) -> tuple[EvidenceTier, ...]:
        return evidence_tiers_for_oracle_verification(self.verification)


@dataclass(frozen=True, slots=True)
class FilterEntry:
    """One entry from the animEffect filter vocabulary SSOT.

    Represents a single `<p:animEffect filter="value">` string value that
    PowerPoint recognises for entrance and exit presets. Loaded from
    ``filter_vocabulary.xml`` at the oracle root.
    """

    value: str
    description: str
    entrance_preset_id: int | None
    entrance_preset_subtype: int | None
    exit_preset_id: int | None
    exit_preset_subtype: int | None
    verification: str
    source: str

    @property
    def evidence_tiers(self) -> tuple[EvidenceTier, ...]:
        return evidence_tiers_for_oracle_verification(self.verification)

    @property
    def is_entrance_only(self) -> bool:
        return self.entrance_preset_id is not None and self.exit_preset_id is None

    @property
    def is_exit_only(self) -> bool:
        return self.exit_preset_id is not None and self.entrance_preset_id is None

    @property
    def is_pseudo(self) -> bool:
        """True for filter values not usable as standalone entrance/exit effects.

        Pseudo-entries (e.g. ``image``) appear in the vocabulary because they
        are valid ``<p:animEffect filter>`` values but carry their semantics
        through the enclosing preset (opacity in preset 9/27, not a standalone
        entrance). Their preset IDs are encoded as -1 in the SSOT.
        """
        return self.entrance_preset_id == -1 and self.exit_preset_id == -1


@dataclass(frozen=True, slots=True)
class AttrNameEntry:
    """One entry from the <p:attrName> vocabulary SSOT.

    Represents a single ``<p:attrName>`` string value that PowerPoint emits
    natively in its own authoring. Loaded from ``attrname_vocabulary.xml``
    at the oracle root.
    """

    value: str
    category: str
    scope: str
    description: str
    used_by: str
    verification: str
    source: str

    @property
    def evidence_tiers(self) -> tuple[EvidenceTier, ...]:
        return evidence_tiers_for_oracle_verification(self.verification)


@dataclass(frozen=True, slots=True)
class DeadPath:
    """One empirically falsified animation shape.

    Represents an XML construct that PPT's parser accepts but its playback
    engine silently drops (or behaves incorrectly). Loaded from
    ``dead_paths.xml`` at the oracle root. Negative-test invariants can
    assert that generated timing never matches any of these shapes.
    """

    id: str
    element: str
    attribute_names: tuple[str, ...]
    attribute_values: tuple[str, ...]
    context: str
    description: str
    verdict: str
    source: str
    replacement_slot: str
    replacement_note: str


@dataclass(frozen=True, slots=True)
class BehaviorFragment:
    """A single behavior fragment to inject into a compound slot.

    ``name`` identifies an XML file under ``emph/behaviors/<name>.xml``.
    ``tokens`` carries the substitution map that satisfies the fragment's
    template placeholders. Every fragment implicitly receives ``SHAPE_ID``
    and ``DURATION_MS`` from the compound's call; other tokens
    (``BEHAVIOR_ID``, ``TO_COLOR``, ``ROTATION_BY`` etc.) must be supplied
    here per-fragment.
    """

    name: str
    tokens: Mapping[str, Any] = field(default_factory=dict)


def _default_root() -> Path:
    return Path(__file__).resolve().parent.parent.parent / "assets" / "animation_oracle"


class AnimationOracle:
    """In-memory view over the parameterised oracle templates."""

    def __init__(self, root: Path | str | None = None) -> None:
        self._root = Path(root) if root is not None else _default_root()
        if not self._root.is_dir():
            raise FileNotFoundError(f"Animation oracle root not found: {self._root}")
        index_path = self._root / "index.json"
        if not index_path.is_file():
            raise FileNotFoundError(f"Animation oracle index missing: {index_path}")
        self._index: dict[str, PresetSlot] = {}
        self._templates: dict[str, str] = {}
        self._filter_vocabulary: tuple[FilterEntry, ...] | None = None
        self._attrname_vocabulary: tuple[AttrNameEntry, ...] | None = None
        self._dead_paths: tuple[DeadPath, ...] | None = None
        self._load_index(index_path)

    # ------------------------------------------------------------------ load

    def _load_index(self, index_path: Path) -> None:
        raw = json.loads(index_path.read_text(encoding="utf-8"))
        slots = raw.get("slots") or {}
        for name, entry in slots.items():
            raw_path = entry.get("path")
            if raw_path is None:
                continue
            template_path = (self._root / raw_path).resolve()
            if not template_path.is_file():
                raise FileNotFoundError(
                    f"Oracle slot '{name}' references missing template {template_path}"
                )
            slot = PresetSlot(
                name=name,
                path=template_path,
                preset_class=entry["preset_class"],
                preset_id=entry.get("preset_id"),
                preset_subtype=entry.get("preset_subtype"),
                bld_mode=entry.get("bld_mode", "animBg"),
                family_signature=entry["family_signature"],
                content_tokens=tuple(entry.get("content_tokens", [])),
                behavior_tokens=tuple(entry.get("behavior_tokens", [])),
                smil_patterns=tuple(entry.get("smil_patterns", [])),
                source=entry.get("source", ""),
                verification=entry.get("verification", "unknown"),
                notes=entry.get("notes", ""),
            )
            self._index[name] = slot
            self._templates[name] = template_path.read_text(encoding="utf-8")

    def _load_filter_vocabulary(self) -> tuple[FilterEntry, ...]:
        vocab_path = self._root / "filter_vocabulary.xml"
        if not vocab_path.is_file():
            raise FileNotFoundError(
                f"Filter vocabulary SSOT missing: {vocab_path}"
            )
        parser = etree.XMLParser(remove_blank_text=True, remove_comments=True)
        root = etree.fromstring(vocab_path.read_bytes(), parser)
        entries: list[FilterEntry] = []
        for filt in root.findall("filter"):
            value = filt.get("value", "")
            description = (filt.findtext("description") or "").strip()
            entrance = filt.find("entrance")
            exit_el = filt.find("exit")
            verification = (filt.findtext("verification") or "unknown").strip()
            source = (filt.findtext("source") or "").strip()

            def _int_or_none(el: etree._Element | None, attr: str) -> int | None:
                if el is None:
                    return None
                raw = el.get(attr)
                if raw is None:
                    return None
                try:
                    return int(raw)
                except ValueError:
                    return None

            entries.append(
                FilterEntry(
                    value=value,
                    description=description,
                    entrance_preset_id=_int_or_none(entrance, "preset-id"),
                    entrance_preset_subtype=_int_or_none(entrance, "preset-subtype"),
                    exit_preset_id=_int_or_none(exit_el, "preset-id"),
                    exit_preset_subtype=_int_or_none(exit_el, "preset-subtype"),
                    verification=verification,
                    source=source,
                )
            )
        return tuple(entries)

    # ---------------------------------------------------------------- access

    @property
    def root(self) -> Path:
        return self._root

    def slots(self) -> list[PresetSlot]:
        return list(self._index.values())

    def filter_vocabulary(self) -> tuple[FilterEntry, ...]:
        """Return the complete animEffect filter vocabulary SSOT.

        Loaded lazily from ``filter_vocabulary.xml`` and cached on first
        access. Each entry describes one filter string value, its
        entrance/exit preset-ID mappings, verification state, and source.
        """
        if self._filter_vocabulary is None:
            self._filter_vocabulary = self._load_filter_vocabulary()
        return self._filter_vocabulary

    def filter_entry(self, value: str) -> FilterEntry:
        """Look up a :class:`FilterEntry` by its ``value`` field."""
        for entry in self.filter_vocabulary():
            if entry.value == value:
                return entry
        raise OracleSlotError(f"Unknown filter vocabulary value: {value!r}")

    # -------------------------------------------------- attrName vocabulary

    def _load_attrname_vocabulary(self) -> tuple[AttrNameEntry, ...]:
        vocab_path = self._root / "attrname_vocabulary.xml"
        if not vocab_path.is_file():
            raise FileNotFoundError(
                f"attrName vocabulary SSOT missing: {vocab_path}"
            )
        parser = etree.XMLParser(remove_blank_text=True, remove_comments=True)
        root = etree.fromstring(vocab_path.read_bytes(), parser)
        entries: list[AttrNameEntry] = []
        for attr_el in root.findall("attrname"):
            entries.append(
                AttrNameEntry(
                    value=attr_el.get("value", ""),
                    category=(attr_el.findtext("category") or "").strip(),
                    scope=(attr_el.findtext("scope") or "").strip(),
                    description=(attr_el.findtext("description") or "").strip(),
                    used_by=(attr_el.findtext("used-by") or "").strip(),
                    verification=(attr_el.findtext("verification") or "unknown").strip(),
                    source=(attr_el.findtext("source") or "").strip(),
                )
            )
        return tuple(entries)

    def attrname_vocabulary(self) -> tuple[AttrNameEntry, ...]:
        """Return the complete <p:attrName> vocabulary SSOT.

        Loaded lazily from ``attrname_vocabulary.xml`` and cached on first
        access. Contains every attrName string PowerPoint emits natively.
        """
        if self._attrname_vocabulary is None:
            self._attrname_vocabulary = self._load_attrname_vocabulary()
        return self._attrname_vocabulary

    def attrname_entry(self, value: str) -> AttrNameEntry:
        """Look up an :class:`AttrNameEntry` by its ``value`` field."""
        for entry in self.attrname_vocabulary():
            if entry.value == value:
                return entry
        raise OracleSlotError(f"Unknown attrName vocabulary value: {value!r}")

    def is_valid_attrname(self, value: str) -> bool:
        """True if *value* appears in the attrName vocabulary SSOT."""
        return any(e.value == value for e in self.attrname_vocabulary())

    # ---------------------------------------------------------- dead paths

    def _load_dead_paths(self) -> tuple[DeadPath, ...]:
        dead_path = self._root / "dead_paths.xml"
        if not dead_path.is_file():
            raise FileNotFoundError(
                f"dead_paths SSOT missing: {dead_path}"
            )
        parser = etree.XMLParser(remove_blank_text=True, remove_comments=True)
        root = etree.fromstring(dead_path.read_bytes(), parser)
        entries: list[DeadPath] = []
        for dp_el in root.findall("dead-path"):
            shape = dp_el.find("shape")
            element_name = ""
            attr_names: list[str] = []
            attr_values: list[str] = []
            context = ""
            if shape is not None:
                element_name = (shape.findtext("element") or "").strip()
                for attr in shape.findall("attribute"):
                    name = attr.get("name", "")
                    if name:
                        attr_names.append(name)
                        attr_values.append((attr.text or "").strip())
                context = (shape.findtext("context") or "").strip()
            replacement = dp_el.find("replacement")
            replacement_slot = ""
            replacement_note = ""
            if replacement is not None:
                replacement_slot = (replacement.findtext("slot") or "").strip()
                replacement_note = (replacement.findtext("note") or "").strip()
            entries.append(
                DeadPath(
                    id=dp_el.get("id", ""),
                    element=element_name,
                    attribute_names=tuple(attr_names),
                    attribute_values=tuple(attr_values),
                    context=context,
                    description=(dp_el.findtext("description") or "").strip(),
                    verdict=(dp_el.findtext("verdict") or "").strip(),
                    source=(dp_el.findtext("source") or "").strip(),
                    replacement_slot=replacement_slot,
                    replacement_note=replacement_note,
                )
            )
        return tuple(entries)

    def dead_paths(self) -> tuple[DeadPath, ...]:
        """Return the empirically-falsified animation shape catalog.

        Loaded lazily from ``dead_paths.xml`` and cached on first access.
        Negative-test invariants should iterate this list to assert that
        generated timing XML never emits any of the listed shapes.
        """
        if self._dead_paths is None:
            self._dead_paths = self._load_dead_paths()
        return self._dead_paths

    def dead_path(self, id: str) -> DeadPath:
        """Look up a :class:`DeadPath` by its ``id`` attribute."""
        for dp in self.dead_paths():
            if dp.id == id:
                return dp
        raise OracleSlotError(f"Unknown dead path id: {id!r}")

    def slot(self, name: str) -> PresetSlot:
        try:
            return self._index[name]
        except KeyError as exc:
            raise OracleSlotError(name) from exc

    def template_text(self, name: str) -> str:
        if name not in self._templates:
            raise OracleSlotError(name)
        return self._templates[name]

    # -------------------------------------------------------- instantiation

    def instantiate(
        self,
        slot_name: str,
        *,
        shape_id: str | int,
        par_id: int,
        duration_ms: int,
        delay_ms: int = 0,
        **tokens: Any,
    ) -> etree._Element:
        """Return a fully substituted ``<p:par>`` element ready for the timing tree.

        Required keyword arguments depend on the slot's ``behavior_tokens`` and
        ``content_tokens`` declared in ``index.json``. Pass them as plain
        keyword arguments using the token name (case-sensitive).
        """
        slot = self.slot(slot_name)
        substitutions: dict[str, str] = {
            "SHAPE_ID": str(shape_id),
            "PAR_ID": str(par_id),
            "DURATION_MS": str(duration_ms),
            "DELAY_MS": str(delay_ms),
        }
        for name in slot.behavior_tokens:
            if name not in tokens:
                raise ValueError(
                    f"Slot '{slot_name}' requires behavior token '{name}'"
                )
            substitutions[name] = str(tokens.pop(name))
        for name in slot.content_tokens:
            if name not in tokens:
                raise ValueError(
                    f"Slot '{slot_name}' requires content token '{name}'"
                )
            substitutions[name] = str(tokens.pop(name))
        if tokens:
            unknown = ", ".join(sorted(tokens))
            raise ValueError(
                f"Unknown tokens for slot '{slot_name}': {unknown}"
            )

        text = self.template_text(slot_name)
        rendered = _render_template(text, substitutions)

        wrapped = (
            f'<root xmlns:p="{NS_P}" '
            f'xmlns:a="{NS_A}">'
            f"{rendered}</root>"
        )
        parser = etree.XMLParser(remove_blank_text=True)
        root = etree.fromstring(wrapped.encode("utf-8"), parser)
        par = root[0]
        par.set(_BUILD_MODE_ATTR, slot.bld_mode)
        # Detach from the synthetic root so the caller owns the element.
        root.remove(par)
        return par

    # --------------------------------------------------------- compound slot

    def instantiate_compound(
        self,
        *,
        shape_id: str | int,
        par_id: int,
        duration_ms: int,
        delay_ms: int = 0,
        behaviors: Sequence[BehaviorFragment | tuple[str, Mapping[str, Any]]],
    ) -> etree._Element:
        """Assemble a compound ``<p:par>`` with arbitrary behavior children.

        This is the primary path for emitting multi-effect animations. Each
        item in *behaviors* is a :class:`BehaviorFragment` (or a
        ``(name, tokens)`` 2-tuple) naming a file under
        ``emph/behaviors/<name>.xml``. Fragments are rendered with their
        own tokens plus implicit ``SHAPE_ID`` / ``DURATION_MS`` (from the
        outer compound call), then appended as direct children of the
        compound's single ``<p:cTn>``.

        The compound slot itself is preset-free — PPT's rendering engine
        walks the ``<p:cTn>``'s ``childTnLst`` and fires every behavior
        element directly. All fragments fire simultaneously on one click.
        """
        base = self.instantiate(
            "emph/compound",
            shape_id=shape_id,
            par_id=par_id,
            duration_ms=duration_ms,
            delay_ms=delay_ms,
        )
        child_tn_lst = base.find(
            f".//{{{NS_P}}}cTn/{{{NS_P}}}childTnLst"
        )
        if child_tn_lst is None:  # pragma: no cover - template guarantees presence
            raise OracleSlotError("emph/compound template is missing <p:childTnLst>")

        for item in behaviors:
            if isinstance(item, BehaviorFragment):
                fragment = item
            else:
                name, tokens = item
                fragment = BehaviorFragment(name=name, tokens=tokens)
            for child in self._render_behavior_fragment(
                fragment,
                shape_id=shape_id,
                duration_ms=duration_ms,
            ):
                child_tn_lst.append(child)

        return base

    # --------------------------------------------------------- flipbook slot

    def instantiate_flipbook(
        self,
        *,
        frame_shape_ids: Sequence[str | int],
        par_id: int,
        duration_ms: int,
        delay_ms: int = 0,
        start_id: int = 100,
    ) -> tuple[etree._Element, list[tuple[str, int]]]:
        """Assemble a flipbook ``<p:par>`` that sequences N pre-rendered frames.

        Each frame is a shape on the slide, all stacked at the same position.
        Frame 0 starts visible; all others start hidden. The flipbook shows
        each frame for ``duration_ms / len(frame_shape_ids)`` milliseconds
        via timed ``<p:set>`` pairs (show at T, hide at T + frame_dur).

        This is the universal fallback for any animation PPT cannot play
        natively: skew, path morph, stroke-width interpolation,
        per-layer opacity, complex filter params, etc. The caller
        pre-renders the keyframes as shapes (custGeom or raster) and
        passes their shape IDs here.

        Returns ``(par_element, bld_entries)`` where *bld_entries* is a list
        of ``(spid, grpId)`` tuples that the caller must emit as
        ``<p:bldP spid="X" grpId="Y" animBg="1"/>`` in the ``<p:bldLst>``.
        The ``grpId`` must match the animation's ``cTn`` group — the standard
        timing-tree builder does not do this automatically for multi-target
        flipbooks.
        """
        n_frames = len(frame_shape_ids)
        if n_frames < 2:
            raise OracleSlotError("Flipbook requires at least 2 frames")

        frame_dur = duration_ms // n_frames
        ctn_id = start_id

        # Build <p:set> elements
        set_children: list[etree._Element] = []

        def _make_set(shape_id: str | int, delay: int, val: str) -> None:
            nonlocal ctn_id
            for child in self._render_behavior_fragment(
                BehaviorFragment(
                    f"flipbook_{'show' if val == 'visible' else 'hide'}",
                    {
                        ("SHOW_ID" if val == "visible" else "HIDE_ID"): str(ctn_id),
                        ("SHOW_DELAY_MS" if val == "visible" else "HIDE_DELAY_MS"): str(delay),
                        "FRAME_SHAPE_ID": str(shape_id),
                    },
                ),
                shape_id=shape_id,
                duration_ms=duration_ms,
            ):
                set_children.append(child)
            ctn_id += 1

        # Hide frames 1..N-1 immediately
        for shape_id in frame_shape_ids[1:]:
            _make_set(shape_id, 0, "hidden")

        # Show/hide sequence
        for i, shape_id in enumerate(frame_shape_ids):
            _make_set(shape_id, i * frame_dur, "visible")
            if i < n_frames - 1:
                _make_set(shape_id, (i + 1) * frame_dur, "hidden")

        # Build the <p:par> wrapper using compound slot
        base = self.instantiate(
            "emph/compound",
            shape_id=frame_shape_ids[0],
            par_id=par_id,
            duration_ms=duration_ms,
            delay_ms=delay_ms,
        )
        child_tn_lst = base.find(
            f".//{{{NS_P}}}cTn/{{{NS_P}}}childTnLst"
        )
        if child_tn_lst is None:
            raise OracleSlotError("emph/compound template missing <p:childTnLst>")

        for child in set_children:
            child_tn_lst.append(child)

        # bldP entries — each frame shape needs grpId matching par_id
        bld_entries = [
            (str(shape_id), par_id) for shape_id in frame_shape_ids
        ]
        return base, bld_entries

    def _render_behavior_fragment(
        self,
        fragment: BehaviorFragment,
        *,
        shape_id: str | int,
        duration_ms: int,
    ) -> list[etree._Element]:
        """Load a behavior fragment file and return its substituted children."""
        fragment_path = self._root / "emph" / "behaviors" / f"{fragment.name}.xml"
        if not fragment_path.is_file():
            raise OracleSlotError(
                f"Behavior fragment '{fragment.name}' not found at {fragment_path}"
            )
        text = fragment_path.read_text(encoding="utf-8")

        substitutions: dict[str, str] = {
            "SHAPE_ID": str(shape_id),
            "DURATION_MS": str(duration_ms),
            "INNER_FILL": "hold",
        }
        for key, value in fragment.tokens.items():
            substitutions[str(key)] = str(value)
        rendered = _render_template(text, substitutions)

        wrapped = (
            f'<root xmlns:p="{NS_P}" xmlns:a="{NS_A}">{rendered}</root>'
        )
        parser = etree.XMLParser(remove_blank_text=True)
        root = etree.fromstring(wrapped.encode("utf-8"), parser)
        fragment_elem = root.find("fragment")
        if fragment_elem is None:
            raise OracleSlotError(
                f"Behavior fragment '{fragment.name}' is missing <fragment> root"
            )
        # Return a list of child elements (the fragment's children become the
        # compound cTn's children). Detach to give ownership to the caller.
        children = list(fragment_elem)
        for child in children:
            fragment_elem.remove(child)
        return children


def _render_template(text: str, substitutions: Mapping[str, str]) -> str:
    # Use a targeted replace loop (not str.format) so literal braces in the
    # template — e.g. within attribute values like JSON blobs — survive.
    rendered = text
    for key, value in substitutions.items():
        rendered = rendered.replace("{" + key + "}", value)
    return rendered


@lru_cache(maxsize=1)
def default_oracle() -> AnimationOracle:
    """Return a process-wide cached :class:`AnimationOracle` instance."""
    return AnimationOracle()
