"""Animation oracle template loader.

Loads the parameterised ``<p:par>`` fragment templates from
``src/svg2ooxml/assets/animation_oracle/`` and substitutes the runtime tokens
each handler needs to specialise a preset for a particular shape.

The oracle is the single source of truth for the XML shape svg2ooxml emits
per PowerPoint animation preset. Handlers should load a slot by name rather
than constructing ``<p:par>`` trees imperatively.

This module also exposes three structured XML SSOT files that describe the
PowerPoint animation vocabulary:

- ``filter_vocabulary.xml`` — the 29-entry ``<p:animEffect filter>`` catalog
  (loaded via :meth:`AnimationOracle.filter_vocabulary`)
- ``attrname_vocabulary.xml`` — the 17 valid ``<p:attrName>`` values
  (loaded via :meth:`AnimationOracle.attrname_vocabulary`)
- ``dead_paths.xml`` — empirically falsified shapes that PPT silently drops
  (loaded via :meth:`AnimationOracle.dead_paths`)

The companion **pptx-animation skill** at ``.claude/skills/pptx-animation/``
(generated by ``tools/build_skill.py``) packages the oracle + these SSOT
files into a Claude-invocable skill with CLI scripts for emitting
entrance, exit, emphasis compound, and motion-path effects, plus a
validator that checks arbitrary XML against ``dead_paths.xml``.

Example::

    oracle = AnimationOracle()
    par = oracle.instantiate(
        "entr/fade",
        shape_id="2",
        par_id=6,
        duration_ms=1500,
        delay_ms=0,
        set_behavior_id=7,
        effect_behavior_id=71,
    )
    # ``par`` is an ``lxml`` element ready to be appended to the timing tree.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any

from lxml import etree

from svg2ooxml.common.boundaries import safe_lxml_parser
from svg2ooxml.drawingml.animation.constants import SVG2_ANIMATION_NS
from svg2ooxml.drawingml.animation.evidence import (
    EvidenceTier,
    evidence_tiers_for_oracle_verification,
)
from svg2ooxml.drawingml.animation.oracle_templates import (
    find_template_tokens,
    render_xml_template,
    resolve_oracle_child_path,
)
from svg2ooxml.drawingml.animation.oracle_vocabulary import (
    AttrNameEntry,
    DeadPath,
    FilterEntry,
    load_attrname_vocabulary,
    load_dead_paths,
    load_filter_vocabulary,
)
from svg2ooxml.drawingml.xml_builder import NS_P

NS_A = "http://schemas.openxmlformats.org/drawingml/2006/main"
_BUILD_MODE_ATTR = f"{{{SVG2_ANIMATION_NS}}}bldMode"

__all__ = [
    "AnimationOracle",
    "AttrNameEntry",
    "BehaviorFragment",
    "DeadPath",
    "EvidenceTier",
    "FilterEntry",
    "OracleSlotError",
    "PresetSlot",
    "default_oracle",
]


class OracleSlotError(KeyError):
    """Raised when a requested oracle slot cannot be resolved."""


@dataclass(frozen=True, slots=True)
class PresetSlot:
    """Metadata describing a single oracle slot."""

    name: str
    path: Path
    preset_class: str
    preset_id: int | None
    preset_subtype: int | None
    bld_mode: str
    family_signature: str
    content_tokens: tuple[str, ...]
    behavior_tokens: tuple[str, ...]
    smil_patterns: tuple[str, ...]
    source: str
    verification: str
    notes: str = ""

    @property
    def evidence_tiers(self) -> tuple[EvidenceTier, ...]:
        return evidence_tiers_for_oracle_verification(self.verification)


@dataclass(frozen=True, slots=True)
class BehaviorFragment:
    """A single behavior fragment to inject into a compound slot.

    ``name`` identifies an XML file under ``emph/behaviors/<name>.xml``.
    ``tokens`` carries the substitution map that satisfies the fragment's
    template placeholders. Every fragment implicitly receives ``SHAPE_ID``
    and ``DURATION_MS`` from the compound's call; other tokens
    (``BEHAVIOR_ID``, ``TO_COLOR``, ``ROTATION_BY`` etc.) must be supplied
    here per-fragment.
    """

    name: str
    tokens: Mapping[str, Any] = field(default_factory=dict)


def _default_root() -> Path:
    return Path(__file__).resolve().parent.parent.parent / "assets" / "animation_oracle"


class AnimationOracle:
    """In-memory view over the parameterised oracle templates."""

    def __init__(self, root: Path | str | None = None) -> None:
        self._root = Path(root) if root is not None else _default_root()
        if not self._root.is_dir():
            raise FileNotFoundError(f"Animation oracle root not found: {self._root}")
        index_path = self._root / "index.json"
        if not index_path.is_file():
            raise FileNotFoundError(f"Animation oracle index missing: {index_path}")
        self._index: dict[str, PresetSlot] = {}
        self._templates: dict[str, str] = {}
        self._filter_vocabulary: tuple[FilterEntry, ...] | None = None
        self._filter_by_value: dict[str, FilterEntry] | None = None
        self._attrname_vocabulary: tuple[AttrNameEntry, ...] | None = None
        self._attrname_by_value: dict[str, AttrNameEntry] | None = None
        self._dead_paths: tuple[DeadPath, ...] | None = None
        self._dead_path_by_id: dict[str, DeadPath] | None = None
        self._load_index(index_path)

    # ------------------------------------------------------------------ load

    def _load_index(self, index_path: Path) -> None:
        raw = json.loads(index_path.read_text(encoding="utf-8"))
        slots = raw.get("slots") or {}
        for name, entry in slots.items():
            raw_path = entry.get("path")
            if raw_path is None:
                continue
            try:
                template_path = resolve_oracle_child_path(self._root, raw_path)
            except ValueError as exc:
                raise OracleSlotError(
                    f"Oracle slot '{name}' references unsafe template path {raw_path!r}"
                ) from exc
            if not template_path.is_file():
                raise FileNotFoundError(
                    f"Oracle slot '{name}' references missing template {template_path}"
                )
            slot = PresetSlot(
                name=name,
                path=template_path,
                preset_class=entry["preset_class"],
                preset_id=entry.get("preset_id"),
                preset_subtype=entry.get("preset_subtype"),
                bld_mode=entry.get("bld_mode", "animBg"),
                family_signature=entry["family_signature"],
                content_tokens=tuple(entry.get("content_tokens", [])),
                behavior_tokens=tuple(entry.get("behavior_tokens", [])),
                smil_patterns=tuple(entry.get("smil_patterns", [])),
                source=entry.get("source", ""),
                verification=entry.get("verification", "unknown"),
                notes=entry.get("notes", ""),
            )
            self._index[name] = slot
            self._templates[name] = template_path.read_text(encoding="utf-8")

    # ---------------------------------------------------------------- access

    @property
    def root(self) -> Path:
        return self._root

    def slots(self) -> list[PresetSlot]:
        return list(self._index.values())

    def filter_vocabulary(self) -> tuple[FilterEntry, ...]:
        """Return the complete animEffect filter vocabulary SSOT.

        Loaded lazily from ``filter_vocabulary.xml`` and cached on first
        access. Each entry describes one filter string value, its
        entrance/exit preset-ID mappings, verification state, and source.
        """
        if self._filter_vocabulary is None:
            self._filter_vocabulary = load_filter_vocabulary(self._root)
            self._filter_by_value = {
                entry.value: entry for entry in self._filter_vocabulary
            }
        return self._filter_vocabulary

    def filter_entry(self, value: str) -> FilterEntry:
        """Look up a :class:`FilterEntry` by its ``value`` field."""
        self.filter_vocabulary()
        if self._filter_by_value is not None and value in self._filter_by_value:
            return self._filter_by_value[value]
        raise OracleSlotError(f"Unknown filter vocabulary value: {value!r}")

    # -------------------------------------------------- attrName vocabulary

    def attrname_vocabulary(self) -> tuple[AttrNameEntry, ...]:
        """Return the complete <p:attrName> vocabulary SSOT.

        Loaded lazily from ``attrname_vocabulary.xml`` and cached on first
        access. Contains every attrName string PowerPoint emits natively.
        """
        if self._attrname_vocabulary is None:
            self._attrname_vocabulary = load_attrname_vocabulary(self._root)
            self._attrname_by_value = {
                entry.value: entry for entry in self._attrname_vocabulary
            }
        return self._attrname_vocabulary

    def attrname_entry(self, value: str) -> AttrNameEntry:
        """Look up an :class:`AttrNameEntry` by its ``value`` field."""
        self.attrname_vocabulary()
        if self._attrname_by_value is not None and value in self._attrname_by_value:
            return self._attrname_by_value[value]
        raise OracleSlotError(f"Unknown attrName vocabulary value: {value!r}")

    def is_valid_attrname(self, value: str) -> bool:
        """True if *value* appears in the attrName vocabulary SSOT."""
        self.attrname_vocabulary()
        return self._attrname_by_value is not None and value in self._attrname_by_value

    # ---------------------------------------------------------- dead paths

    def dead_paths(self) -> tuple[DeadPath, ...]:
        """Return the empirically-falsified animation shape catalog.

        Loaded lazily from ``dead_paths.xml`` and cached on first access.
        Negative-test invariants should iterate this list to assert that
        generated timing XML never emits any of the listed shapes.
        """
        if self._dead_paths is None:
            self._dead_paths = load_dead_paths(self._root)
            self._dead_path_by_id = {entry.id: entry for entry in self._dead_paths}
        return self._dead_paths

    def dead_path(self, id: str) -> DeadPath:
        """Look up a :class:`DeadPath` by its ``id`` attribute."""
        self.dead_paths()
        if self._dead_path_by_id is not None and id in self._dead_path_by_id:
            return self._dead_path_by_id[id]
        raise OracleSlotError(f"Unknown dead path id: {id!r}")

    def slot(self, name: str) -> PresetSlot:
        try:
            return self._index[name]
        except KeyError as exc:
            raise OracleSlotError(name) from exc

    def template_text(self, name: str) -> str:
        if name not in self._templates:
            raise OracleSlotError(name)
        return self._templates[name]

    # -------------------------------------------------------- instantiation

    def instantiate(
        self,
        slot_name: str,
        *,
        shape_id: str | int,
        par_id: int,
        duration_ms: int,
        delay_ms: int = 0,
        **tokens: Any,
    ) -> etree._Element:
        """Return a fully substituted ``<p:par>`` element ready for the timing tree.

        Required keyword arguments depend on the slot's ``behavior_tokens`` and
        ``content_tokens`` declared in ``index.json``. Pass them as plain
        keyword arguments using the token name (case-sensitive).
        """
        slot = self.slot(slot_name)
        substitutions: dict[str, str] = {
            "SHAPE_ID": str(shape_id),
            "PAR_ID": str(par_id),
            "DURATION_MS": str(duration_ms),
            "DELAY_MS": str(delay_ms),
        }
        for name in slot.behavior_tokens:
            if name not in tokens:
                raise ValueError(
                    f"Slot '{slot_name}' requires behavior token '{name}'"
                )
            substitutions[name] = str(tokens.pop(name))
        for name in slot.content_tokens:
            if name not in tokens:
                raise ValueError(
                    f"Slot '{slot_name}' requires content token '{name}'"
                )
            substitutions[name] = str(tokens.pop(name))
        if tokens:
            unknown = ", ".join(sorted(tokens))
            raise ValueError(
                f"Unknown tokens for slot '{slot_name}': {unknown}"
            )

        text = self.template_text(slot_name)
        rendered = render_xml_template(text, substitutions)

        wrapped = (
            f'<root xmlns:p="{NS_P}" '
            f'xmlns:a="{NS_A}">'
            f"{rendered}</root>"
        )
        parser = safe_lxml_parser(remove_blank_text=True)
        root = etree.fromstring(wrapped.encode("utf-8"), parser)
        par = root[0]
        par.set(_BUILD_MODE_ATTR, slot.bld_mode)
        # Detach from the synthetic root so the caller owns the element.
        root.remove(par)
        return par

    # --------------------------------------------------------- compound slot

    def instantiate_compound(
        self,
        *,
        shape_id: str | int,
        par_id: int,
        duration_ms: int,
        delay_ms: int = 0,
        behaviors: Sequence[BehaviorFragment | tuple[str, Mapping[str, Any]]],
    ) -> etree._Element:
        """Assemble a compound ``<p:par>`` with arbitrary behavior children.

        This is the primary path for emitting multi-effect animations. Each
        item in *behaviors* is a :class:`BehaviorFragment` (or a
        ``(name, tokens)`` 2-tuple) naming a file under
        ``emph/behaviors/<name>.xml``. Fragments are rendered with their
        own tokens plus implicit ``SHAPE_ID`` / ``DURATION_MS`` (from the
        outer compound call), then appended as direct children of the
        compound's single ``<p:cTn>``.

        The compound slot itself is preset-free — PPT's rendering engine
        walks the ``<p:cTn>``'s ``childTnLst`` and fires every behavior
        element directly. All fragments fire simultaneously on one click.
        """
        base = self.instantiate(
            "emph/compound",
            shape_id=shape_id,
            par_id=par_id,
            duration_ms=duration_ms,
            delay_ms=delay_ms,
        )
        child_tn_lst = base.find(
            f".//{{{NS_P}}}cTn/{{{NS_P}}}childTnLst"
        )
        if child_tn_lst is None:  # pragma: no cover - template guarantees presence
            raise OracleSlotError("emph/compound template is missing <p:childTnLst>")

        for item in behaviors:
            if isinstance(item, BehaviorFragment):
                fragment = item
            else:
                name, tokens = item
                fragment = BehaviorFragment(name=name, tokens=tokens)
            for child in self._render_behavior_fragment(
                fragment,
                shape_id=shape_id,
                duration_ms=duration_ms,
            ):
                child_tn_lst.append(child)

        return base

    # --------------------------------------------------------- flipbook slot

    def instantiate_flipbook(
        self,
        *,
        frame_shape_ids: Sequence[str | int],
        par_id: int,
        duration_ms: int,
        delay_ms: int = 0,
        start_id: int = 100,
    ) -> tuple[etree._Element, list[tuple[str, int]]]:
        """Assemble a flipbook ``<p:par>`` that sequences N pre-rendered frames.

        Each frame is a shape on the slide, all stacked at the same position.
        Frame 0 starts visible; all others start hidden. The flipbook shows
        each frame for ``duration_ms / len(frame_shape_ids)`` milliseconds
        via timed ``<p:set>`` pairs (show at T, hide at T + frame_dur).

        This is the universal fallback for any animation PPT cannot play
        natively: skew, path morph, stroke-width interpolation,
        per-layer opacity, complex filter params, etc. The caller
        pre-renders the keyframes as shapes (custGeom or raster) and
        passes their shape IDs here.

        Returns ``(par_element, bld_entries)`` where *bld_entries* is a list
        of ``(spid, grpId)`` tuples that the caller must emit as
        ``<p:bldP spid="X" grpId="Y" animBg="1"/>`` in the ``<p:bldLst>``.
        The ``grpId`` must match the animation's ``cTn`` group — the standard
        timing-tree builder does not do this automatically for multi-target
        flipbooks.
        """
        n_frames = len(frame_shape_ids)
        if n_frames < 2:
            raise OracleSlotError("Flipbook requires at least 2 frames")

        frame_dur = duration_ms // n_frames
        ctn_id = start_id

        # Build <p:set> elements
        set_children: list[etree._Element] = []

        def _make_set(shape_id: str | int, delay: int, val: str) -> None:
            nonlocal ctn_id
            for child in self._render_behavior_fragment(
                BehaviorFragment(
                    f"flipbook_{'show' if val == 'visible' else 'hide'}",
                    {
                        ("SHOW_ID" if val == "visible" else "HIDE_ID"): str(ctn_id),
                        ("SHOW_DELAY_MS" if val == "visible" else "HIDE_DELAY_MS"): str(delay),
                        "FRAME_SHAPE_ID": str(shape_id),
                    },
                ),
                shape_id=shape_id,
                duration_ms=duration_ms,
            ):
                set_children.append(child)
            ctn_id += 1

        # Hide frames 1..N-1 immediately
        for shape_id in frame_shape_ids[1:]:
            _make_set(shape_id, 0, "hidden")

        # Show/hide sequence
        for i, shape_id in enumerate(frame_shape_ids):
            _make_set(shape_id, i * frame_dur, "visible")
            if i < n_frames - 1:
                _make_set(shape_id, (i + 1) * frame_dur, "hidden")

        # Build the <p:par> wrapper using compound slot
        base = self.instantiate(
            "emph/compound",
            shape_id=frame_shape_ids[0],
            par_id=par_id,
            duration_ms=duration_ms,
            delay_ms=delay_ms,
        )
        child_tn_lst = base.find(
            f".//{{{NS_P}}}cTn/{{{NS_P}}}childTnLst"
        )
        if child_tn_lst is None:
            raise OracleSlotError("emph/compound template missing <p:childTnLst>")

        for child in set_children:
            child_tn_lst.append(child)

        # bldP entries — each frame shape needs grpId matching par_id
        bld_entries = [
            (str(shape_id), par_id) for shape_id in frame_shape_ids
        ]
        return base, bld_entries

    def _render_behavior_fragment(
        self,
        fragment: BehaviorFragment,
        *,
        shape_id: str | int,
        duration_ms: int,
    ) -> list[etree._Element]:
        """Load a behavior fragment file and return its substituted children."""
        try:
            behavior_root = resolve_oracle_child_path(self._root, "emph", "behaviors")
            fragment_path = resolve_oracle_child_path(
                behavior_root,
                f"{fragment.name}.xml",
            )
        except ValueError as exc:
            raise OracleSlotError(
                f"Behavior fragment '{fragment.name}' escapes oracle root"
            ) from exc
        if not fragment_path.is_file():
            raise OracleSlotError(
                f"Behavior fragment '{fragment.name}' not found at {fragment_path}"
            )
        text = fragment_path.read_text(encoding="utf-8")

        substitutions: dict[str, str] = {
            "SHAPE_ID": str(shape_id),
            "DURATION_MS": str(duration_ms),
            "INNER_FILL": "hold",
        }
        for key, value in fragment.tokens.items():
            substitutions[str(key)] = str(value)
        template_tokens = find_template_tokens(text)
        extra_tokens = set(map(str, fragment.tokens)) - template_tokens
        if extra_tokens:
            raise ValueError(
                f"Behavior fragment '{fragment.name}' got unknown tokens: "
                f"{', '.join(sorted(extra_tokens))}"
            )
        rendered = render_xml_template(text, substitutions)

        wrapped = (
            f'<root xmlns:p="{NS_P}" xmlns:a="{NS_A}">{rendered}</root>'
        )
        parser = safe_lxml_parser(remove_blank_text=True)
        root = etree.fromstring(wrapped.encode("utf-8"), parser)
        fragment_elem = root.find("fragment")
        if fragment_elem is None:
            raise OracleSlotError(
                f"Behavior fragment '{fragment.name}' is missing <fragment> root"
            )
        # Return a list of child elements (the fragment's children become the
        # compound cTn's children). Detach to give ownership to the caller.
        children = list(fragment_elem)
        for child in children:
            fragment_elem.remove(child)
        return children


@lru_cache(maxsize=1)
def default_oracle() -> AnimationOracle:
    """Return a process-wide cached :class:`AnimationOracle` instance."""
    return AnimationOracle()
