# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'clear_providers',
    'ensure_default_providers',
    'get_provider',
    'get_provider_factories',
    'iter_providers',
    'register_provider',
    'color_provider',
    'drawingml_provider',
    'filter_provider',
    'font_provider',
    'gradient_provider',
    'hyperlink_provider',
    'image_provider',
    'marker_provider',
    'mask_provider',
    'pattern_provider',
    'registry',
    'symbol_provider'
]

# map symbol -> relative module
_symbol_map = {'get_provider': 'registry', 'clear_providers': 'registry', 'register_provider': 'registry', 'iter_providers': 'registry', 'ensure_default_providers': 'registry', 'get_provider_factories': 'registry'}
_module_map = {'color_provider': 'color_provider', 'drawingml_provider': 'drawingml_provider', 'filter_provider': 'filter_provider', 'font_provider': 'font_provider', 'gradient_provider': 'gradient_provider', 'hyperlink_provider': 'hyperlink_provider', 'image_provider': 'image_provider', 'marker_provider': 'marker_provider', 'mask_provider': 'mask_provider', 'pattern_provider': 'pattern_provider', 'registry': 'registry', 'symbol_provider': 'symbol_provider'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
