# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'CheckoutRequest',
    'CheckoutResponse',
    'ExportRequest',
    'ExportResponse',
    'JobStatusResponse',
    'PortalResponse',
    'RequestedFont',
    'SVGFrame',
    'SubscriptionInfo',
    'SubscriptionStatusResponse',
    'UsageInfo',
    'export',
    'subscription'
]

# map symbol -> relative module
_symbol_map = {'ExportResponse': 'export', 'ExportRequest': 'export', 'RequestedFont': 'export', 'JobStatusResponse': 'export', 'SVGFrame': 'export', 'CheckoutResponse': 'subscription', 'PortalResponse': 'subscription', 'SubscriptionInfo': 'subscription', 'CheckoutRequest': 'subscription', 'UsageInfo': 'subscription', 'SubscriptionStatusResponse': 'subscription'}
_module_map = {'export': 'export', 'subscription': 'subscription'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
