# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ARC_TO',
    'Arc',
    'CLOSE',
    'CUBIC_TO',
    'ClosePath',
    'CubicCurve',
    'H_LINE_TO',
    'LINE_TO',
    'LineTo',
    'MOVE_TO',
    'Matrix',
    'MoveTo',
    'NormalizedPath',
    'PathCommand',
    'QUAD_TO',
    'QuadraticCurve',
    'SMOOTH_CUBIC_TO',
    'SMOOTH_QUAD_TO',
    'TessellationResult',
    'Tessellator',
    'V_LINE_TO',
    'Vec2',
    'matrix_from_commands',
    'normalize_path',
    'matrix',
    'path_commands',
    'path_normalizer',
    'primitives',
    'tessellation',
    'vectors'
]

# map symbol -> relative module
_symbol_map = {'Matrix': 'matrix', 'matrix_from_commands': 'matrix', 'MOVE_TO': 'path_commands', 'SMOOTH_QUAD_TO': 'path_commands', 'QUAD_TO': 'path_commands', 'CUBIC_TO': 'path_commands', 'H_LINE_TO': 'path_commands', 'SMOOTH_CUBIC_TO': 'path_commands', 'LINE_TO': 'path_commands', 'CLOSE': 'path_commands', 'V_LINE_TO': 'path_commands', 'ARC_TO': 'path_commands', 'normalize_path': 'path_normalizer', 'NormalizedPath': 'path_normalizer', 'PathCommand': 'path_normalizer', 'LineTo': 'primitives', 'ClosePath': 'primitives', 'QuadraticCurve': 'primitives', 'Arc': 'primitives', 'MoveTo': 'primitives', 'CubicCurve': 'primitives', 'Tessellator': 'tessellation', 'TessellationResult': 'tessellation', 'Vec2': 'vectors'}
_module_map = {'matrix': 'matrix', 'path_commands': 'path_commands', 'path_normalizer': 'path_normalizer', 'primitives': 'primitives', 'tessellation': 'tessellation', 'vectors': 'vectors'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
