# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ConversionArtifacts',
    'ExportService',
    'ExportServiceDependencies',
    'ExportStatus',
    'FakeBlob',
    'FakeBucket',
    'FakeCollectionReference',
    'FakeDocumentReference',
    'FakeDocumentSnapshot',
    'FakeFirestoreClient',
    'FakeStorageClient',
    'FontDiagnostics',
    'FontPreparationResult',
    'JobNotFoundError',
    'OfflineFontFetcher',
    'SlidesPublishResult',
    'SlidesPublishingError',
    'StripeService',
    'SubscriptionRepository',
    'build_export_service_dependencies',
    'collect_font_diagnostics',
    'render_pptx_for_frames',
    'upload_pptx_to_slides',
    'converter',
    'dependencies',
    'export_service',
    'fakes',
    'slides_publisher',
    'stripe_service',
    'subscription_repository'
]

# map symbol -> relative module
_symbol_map = {'FontDiagnostics': 'converter', 'ConversionArtifacts': 'converter', 'collect_font_diagnostics': 'converter', 'render_pptx_for_frames': 'converter', 'build_export_service_dependencies': 'dependencies', 'ExportServiceDependencies': 'dependencies', 'JobNotFoundError': 'export_service', 'ExportService': 'export_service', 'FontPreparationResult': 'export_service', 'ExportStatus': 'export_service', 'FakeBucket': 'fakes', 'FakeStorageClient': 'fakes', 'FakeDocumentReference': 'fakes', 'OfflineFontFetcher': 'fakes', 'FakeBlob': 'fakes', 'FakeDocumentSnapshot': 'fakes', 'FakeCollectionReference': 'fakes', 'FakeFirestoreClient': 'fakes', 'upload_pptx_to_slides': 'slides_publisher', 'SlidesPublishingError': 'slides_publisher', 'SlidesPublishResult': 'slides_publisher', 'StripeService': 'stripe_service', 'SubscriptionRepository': 'subscription_repository'}
_module_map = {'converter': 'converter', 'dependencies': 'dependencies', 'export_service': 'export_service', 'fakes': 'fakes', 'slides_publisher': 'slides_publisher', 'stripe_service': 'stripe_service', 'subscription_repository': 'subscription_repository'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
