# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'NormalizedSegments',
    'PathCommand',
    'PathParseError',
    'PathTessellation',
    'TessellationOutput',
    'approximate_circle',
    'approximate_ellipse',
    'build_path_commands',
    'compute_path_bounds',
    'compute_segments_bbox',
    'normalize_path_to_segments',
    'parse_path_data',
    'tessellate_path',
    'to_line_segments',
    'drawing',
    'drawingml',
    'parser',
    'resvg_bridge',
    'segments'
]

# map symbol -> relative module
_symbol_map = {'approximate_ellipse': 'drawing', 'approximate_circle': 'drawing', 'to_line_segments': 'drawing', 'compute_path_bounds': 'drawingml', 'build_path_commands': 'drawingml', 'PathCommand': 'drawingml', 'PathParseError': 'parser', 'parse_path_data': 'parser', 'TessellationOutput': 'resvg_bridge', 'PathTessellation': 'resvg_bridge', 'NormalizedSegments': 'resvg_bridge', 'normalize_path_to_segments': 'resvg_bridge', 'tessellate_path': 'resvg_bridge', 'compute_segments_bbox': 'segments'}
_module_map = {'drawing': 'drawing', 'drawingml': 'drawingml', 'parser': 'parser', 'resvg_bridge': 'resvg_bridge', 'segments': 'segments'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
