# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ConversionContext',
    'DEFAULT_DPI',
    'EMU_PER_CM',
    'EMU_PER_INCH',
    'EMU_PER_MM',
    'EMU_PER_PICA',
    'EMU_PER_POINT',
    'EMU_PER_PX_AT_DEFAULT_DPI',
    'EMU_PER_Q',
    'LengthConverter',
    'PX_PER_INCH',
    'UnitConverter',
    'emu_to_px',
    'emu_to_unit',
    'px_to_emu',
    'conversion',
    'converters',
    'scalars'
]

# map symbol -> relative module
_symbol_map = {'ConversionContext': 'conversion', 'UnitConverter': 'conversion', 'emu_to_unit': 'conversion', 'px_to_emu': 'conversion', 'EMU_PER_INCH': 'conversion', 'EMU_PER_MM': 'conversion', 'EMU_PER_Q': 'conversion', 'EMU_PER_CM': 'conversion', 'emu_to_px': 'conversion', 'EMU_PER_PX_AT_DEFAULT_DPI': 'conversion', 'EMU_PER_PICA': 'conversion', 'EMU_PER_POINT': 'conversion', 'DEFAULT_DPI': 'conversion', 'LengthConverter': 'converters', 'PX_PER_INCH': 'scalars'}
_module_map = {'conversion': 'conversion', 'converters': 'converters', 'scalars': 'scalars'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
