# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ConversionContext',
    'LengthConverter',
    'UnitConverter',
    'emu_to_px',
    'emu_to_unit',
    'px_to_emu',
    'conversion',
    'converters',
    'scalars'
]

# map symbol -> relative module
_symbol_map = {'UnitConverter': 'conversion', 'emu_to_px': 'conversion', 'emu_to_unit': 'conversion', 'ConversionContext': 'conversion', 'px_to_emu': 'conversion', 'LengthConverter': 'converters'}
_module_map = {'conversion': 'conversion', 'converters': 'converters', 'scalars': 'scalars'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
