# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'CSSFontFaceParser',
    'ConversionContext',
    'DEFAULT_NAMESPACES',
    'EXTERNAL_PROTOCOLS',
    'NormalizationSettings',
    'ParseResult',
    'ParserConfig',
    'ParserOptions',
    'ParserReferences',
    'SVGParser',
    'SafeSVGNormalizer',
    'StyleContext',
    'SwitchEvaluator',
    'UnitConverter',
    'XMLParser',
    'XML_DECLARATION',
    'build_style_context',
    'children',
    'collect_namespaces',
    'collect_references',
    'compute_statistics',
    'ensure_namespaces',
    'ensure_svg_root',
    'fix_encoding_issues',
    'has_basic_dimensions',
    'has_external_references',
    'load_dom',
    'parse_color',
    'prepare_svg_content',
    'resolve_viewport',
    'sanitize_svg',
    'viewbox_to_px',
    'walk',
    'batch',
    'colors',
    'content_cleaner',
    'css_font_parser',
    'dom_loader',
    'normalization',
    'preprocess',
    'reference_collector',
    'references',
    'result',
    'sanitizers',
    'split',
    'statistics',
    'style_context',
    'svg_parser',
    'switch_evaluator',
    'units',
    'validators',
    'xml_utils'
]

# map symbol -> relative module
_symbol_map = {'fix_encoding_issues': 'content_cleaner', 'prepare_svg_content': 'content_cleaner', 'XML_DECLARATION': 'content_cleaner', 'parse_color': 'colors.parsing', 'CSSFontFaceParser': 'css_font_parser', 'ParserOptions': 'dom_loader', 'load_dom': 'dom_loader', 'XMLParser': 'dom_loader', 'SafeSVGNormalizer': 'normalization', 'NormalizationSettings': 'normalization', 'ParserReferences': 'reference_collector', 'collect_references': 'reference_collector', 'has_external_references': 'references', 'EXTERNAL_PROTOCOLS': 'references', 'collect_namespaces': 'references', 'ParseResult': 'result', 'sanitize_svg': 'sanitizers', 'compute_statistics': 'statistics', 'StyleContext': 'style_context', 'resolve_viewport': 'style_context', 'build_style_context': 'style_context', 'SVGParser': 'svg_parser', 'ParserConfig': 'svg_parser', 'SwitchEvaluator': 'switch_evaluator', 'ConversionContext': 'units', 'UnitConverter': 'units', 'viewbox_to_px': 'units', 'ensure_namespaces': 'validators', 'has_basic_dimensions': 'validators', 'DEFAULT_NAMESPACES': 'validators', 'ensure_svg_root': 'validators', 'children': 'xml_utils', 'walk': 'xml_utils'}
_module_map = {'batch': 'batch', 'colors': 'colors', 'content_cleaner': 'content_cleaner', 'css_font_parser': 'css_font_parser', 'dom_loader': 'dom_loader', 'normalization': 'normalization', 'preprocess': 'preprocess', 'reference_collector': 'reference_collector', 'references': 'references', 'result': 'result', 'sanitizers': 'sanitizers', 'split': 'split', 'statistics': 'statistics', 'style_context': 'style_context', 'svg_parser': 'svg_parser', 'switch_evaluator': 'switch_evaluator', 'units': 'units', 'validators': 'validators', 'xml_utils': 'xml_utils'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
