# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'AnimationComplexity',
    'AnimationDefinition',
    'AnimationKeyframe',
    'AnimationScene',
    'AnimationSummary',
    'AnimationTiming',
    'AnimationType',
    'BezierSegment',
    'BlurEffect',
    'CalcMode',
    'CharacterPlacement',
    'Circle',
    'ClipRef',
    'ClipStrategy',
    'CustomEffect',
    'EMU_PER_POINT',
    'Effect',
    'Ellipse',
    'EmbeddedFontPlan',
    'EnhancedRun',
    'FillMode',
    'FontAvailability',
    'FontFaceRule',
    'FontFaceSrc',
    'FontMetadata',
    'FontMetrics',
    'FontStrategy',
    'GlowEffect',
    'GradientPaintRef',
    'GradientStop',
    'Group',
    'Image',
    'Line',
    'LineSegment',
    'LinearGradientPaint',
    'MaskDefinition',
    'MaskInstance',
    'MaskMode',
    'MaskRef',
    'Path',
    'PathPoint',
    'PatternPaint',
    'Point',
    'Polygon',
    'Polyline',
    'RadialGradientPaint',
    'Rect',
    'Rectangle',
    'ReflectionEffect',
    'Run',
    'Scene',
    'Segment',
    'ShadowEffect',
    'SoftEdgeEffect',
    'SolidPaint',
    'Stroke',
    'StrokeCap',
    'StrokeJoin',
    'TextAnchor',
    'TextFrame',
    'TextPathFrame',
    'TextPathMethod',
    'TextPathSide',
    'TextPathSpacing',
    'TransformType',
    'WordArtCandidate',
    'convert_parser_output',
    'format_transform_string',
    'animation',
    'effects',
    'entrypoints',
    'font_metadata',
    'fonts',
    'geometry',
    'numpy_compat',
    'paint',
    'scene',
    'shapes',
    'text',
    'text_path'
]

# map symbol -> relative module
_symbol_map = {'FillMode': 'animation', 'AnimationDefinition': 'animation', 'TransformType': 'animation', 'AnimationType': 'animation', 'AnimationScene': 'animation', 'AnimationSummary': 'animation', 'AnimationTiming': 'animation', 'format_transform_string': 'animation', 'CalcMode': 'animation', 'AnimationComplexity': 'animation', 'AnimationKeyframe': 'animation', 'EMU_PER_POINT': 'effects', 'ReflectionEffect': 'effects', 'CustomEffect': 'effects', 'GlowEffect': 'effects', 'ShadowEffect': 'effects', 'Effect': 'effects', 'BlurEffect': 'effects', 'SoftEdgeEffect': 'effects', 'convert_parser_output': 'entrypoints', 'FontMetadata': 'font_metadata', 'FontAvailability': 'font_metadata', 'FontMetrics': 'font_metadata', 'FontStrategy': 'font_metadata', 'FontFaceRule': 'fonts', 'FontFaceSrc': 'fonts', 'LineSegment': 'geometry', 'BezierSegment': 'geometry', 'Segment': 'geometry', 'Point': 'geometry', 'Rect': 'geometry', 'StrokeCap': 'paint', 'LinearGradientPaint': 'paint', 'GradientPaintRef': 'paint', 'SolidPaint': 'paint', 'StrokeJoin': 'paint', 'Stroke': 'paint', 'GradientStop': 'paint', 'PatternPaint': 'paint', 'RadialGradientPaint': 'paint', 'MaskRef': 'scene', 'Group': 'scene', 'MaskInstance': 'scene', 'Image': 'scene', 'MaskDefinition': 'scene', 'Scene': 'scene', 'ClipRef': 'scene', 'MaskMode': 'scene', 'ClipStrategy': 'scene', 'Path': 'scene', 'Rectangle': 'shapes', 'Line': 'shapes', 'Polygon': 'shapes', 'Ellipse': 'shapes', 'Circle': 'shapes', 'Polyline': 'shapes', 'EmbeddedFontPlan': 'text', 'TextAnchor': 'text', 'Run': 'text', 'WordArtCandidate': 'text', 'EnhancedRun': 'text', 'TextFrame': 'text', 'CharacterPlacement': 'text_path', 'TextPathSide': 'text_path', 'TextPathSpacing': 'text_path', 'TextPathFrame': 'text_path', 'PathPoint': 'text_path', 'TextPathMethod': 'text_path'}
_module_map = {'animation': 'animation', 'effects': 'effects', 'entrypoints': 'entrypoints', 'font_metadata': 'font_metadata', 'fonts': 'fonts', 'geometry': 'geometry', 'numpy_compat': 'numpy_compat', 'paint': 'paint', 'scene': 'scene', 'shapes': 'shapes', 'text': 'text', 'text_path': 'text_path'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
