# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ADVANCED_COLOR_ENGINE_AVAILABLE',
    'AdvancedColor',
    'BasicColorInput',
    'BlendMode',
    'CSS3_NAMES_TO_HEX',
    'Color',
    'ColorAccessibility',
    'ColorBatch',
    'ColorBlindnessType',
    'ColorHarmony',
    'ColorManipulation',
    'ColorParser',
    'ColorSpaceConverter',
    'ColorSpaceResult',
    'ContrastLevel',
    'MAX_OKLAB_DISTANCE',
    'PIL_AVAILABLE',
    'TRANSPARENT',
    'color_to_hex',
    'require_color_engine',
    'ensure_advanced_color_engine',
    'from_advanced_color',
    'oklab_to_oklch',
    'oklab_to_rgb',
    'oklch_to_oklab',
    'oklch_to_rgb',
    'parse_color',
    'rgb_to_oklab',
    'rgb_to_oklch',
    'summarize_palette',
    'to_advanced_color',
    'advanced',
    'analysis',
    'bridge',
    'models',
    'names',
    'oklab',
    'palettes',
    'parsers',
    'spaces',
    'utils'
]

# map symbol -> relative module
_symbol_map = {
    'MAX_OKLAB_DISTANCE': 'analysis',
    'summarize_palette': 'analysis',
    'from_advanced_color': 'bridge',
    'to_advanced_color': 'bridge',
    'ensure_advanced_color_engine': 'bridge',
    'BasicColorInput': 'bridge',
    'ADVANCED_COLOR_ENGINE_AVAILABLE': 'bridge',
    'Color': 'models',
    'TRANSPARENT': 'models',
    'CSS3_NAMES_TO_HEX': 'names',
    'oklch_to_oklab': 'oklab',
    'oklab_to_oklch': 'oklab',
    'oklab_to_rgb': 'oklab',
    'oklch_to_rgb': 'oklab',
    'rgb_to_oklch': 'oklab',
    'rgb_to_oklab': 'oklab',
    'parse_color': 'parsers',
    'PIL_AVAILABLE': 'spaces',
    'ColorSpaceConverter': 'spaces',
    'ColorSpaceResult': 'spaces',
    'color_to_hex': 'utils',
    'AdvancedColor': 'advanced',
    'BlendMode': 'advanced',
    'require_color_engine': 'advanced',
    'ColorAccessibility': 'advanced',
    'ColorBatch': 'advanced',
    'ColorBlindnessType': 'advanced',
    'ColorHarmony': 'advanced',
    'ColorManipulation': 'advanced',
    'ColorParser': 'advanced',
    'ContrastLevel': 'advanced'
}
_module_map = {'advanced': 'advanced', 'analysis': 'analysis', 'bridge': 'bridge', 'models': 'models', 'names': 'names', 'oklab': 'oklab', 'palettes': 'palettes', 'parsers': 'parsers', 'spaces': 'spaces', 'utils': 'utils'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
