# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'BezierEasing',
    'ColorInterpolator',
    'DEFAULT_TMP_DIR',
    'InterpolationEngine',
    'InterpolationResult',
    'NumericInterpolator',
    'PROJECT_ROOT',
    'ShapeData',
    'TransformInterpolator',
    'parse_time_value',
    'project_temp_dir',
    'temporary_directory',
    'interpolation',
    'tempfiles',
    'time',
    'types'
]

# map symbol -> relative module
_symbol_map = {'InterpolationEngine': 'interpolation', 'InterpolationResult': 'interpolation', 'ColorInterpolator': 'interpolation', 'BezierEasing': 'interpolation', 'NumericInterpolator': 'interpolation', 'TransformInterpolator': 'interpolation', 'PROJECT_ROOT': 'tempfiles', 'project_temp_dir': 'tempfiles', 'DEFAULT_TMP_DIR': 'tempfiles', 'temporary_directory': 'tempfiles', 'parse_time_value': 'time', 'ShapeData': 'types'}
_module_map = {'interpolation': 'interpolation', 'tempfiles': 'tempfiles', 'time': 'time', 'types': 'types'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
