# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'BezierEasing',
    'ColorInterpolator',
    'DEFAULT_TMP_DIR',
    'InterpolationEngine',
    'InterpolationResult',
    'NumericInterpolator',
    'PROJECT_ROOT',
    'ShapeData',
    'TransformInterpolator',
    'parse_time_value',
    'project_temp_dir',
    'temporary_directory',
    'compat',
    'conversions',
    'geometry',
    'geometry.algorithms',
    'geometry.clip',
    'geometry.fractional',
    'geometry.paths',
    'geometry.transforms',
    'interpolation',
    'style',
    'tempfiles',
    'time',
    'types',
    'units'
]

# map symbol -> relative module
_symbol_map = {'BezierEasing': 'interpolation', 'TransformInterpolator': 'interpolation', 'InterpolationEngine': 'interpolation', 'InterpolationResult': 'interpolation', 'NumericInterpolator': 'interpolation', 'ColorInterpolator': 'interpolation', 'project_temp_dir': 'tempfiles', 'DEFAULT_TMP_DIR': 'tempfiles', 'PROJECT_ROOT': 'tempfiles', 'temporary_directory': 'tempfiles', 'parse_time_value': 'time', 'ShapeData': 'types'}
_module_map = {'compat': 'compat', 'conversions': 'conversions', 'geometry': 'geometry', 'geometry.algorithms': 'geometry.algorithms', 'geometry.clip': 'geometry.clip', 'geometry.fractional': 'geometry.fractional', 'geometry.paths': 'geometry.paths', 'geometry.transforms': 'geometry.transforms', 'interpolation': 'interpolation', 'style': 'style', 'tempfiles': 'tempfiles', 'time': 'time', 'types': 'types', 'units': 'units'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
