# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'CoordinateValidationError',
    'DEFAULT_DPI',
    'EMUBoundaryError',
    'EMU_PER_CM',
    'EMU_PER_INCH',
    'EMU_PER_MM',
    'EMU_PER_POINT',
    'FractionalEMUConverter',
    'FractionalEMUError',
    'MAX_EMU_VALUE',
    'MIN_EMU_VALUE',
    'PrecisionContext',
    'PrecisionMetrics',
    'PrecisionMode',
    'PrecisionOverflowError',
    'constants',
    'converter',
    'errors',
    'precision',
    'types'
]

# map symbol -> relative module
_symbol_map = {'EMU_PER_CM': 'constants', 'DEFAULT_DPI': 'constants', 'EMU_PER_INCH': 'constants', 'EMU_PER_MM': 'constants', 'MIN_EMU_VALUE': 'constants', 'EMU_PER_POINT': 'constants', 'MAX_EMU_VALUE': 'constants', 'FractionalEMUConverter': 'converter', 'EMUBoundaryError': 'errors', 'PrecisionOverflowError': 'errors', 'CoordinateValidationError': 'errors', 'FractionalEMUError': 'errors', 'PrecisionMetrics': 'precision', 'PrecisionContext': 'types', 'PrecisionMode': 'types'}
_module_map = {'constants': 'constants', 'converter': 'converter', 'errors': 'errors', 'precision': 'precision', 'types': 'types'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
