# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ClipPathContext',
    'ComponentTransferFunction',
    'ComponentTransferPlan',
    'FilterPlan',
    'FilterPrimitivePlan',
    'MarkerPlacement',
    'MaskContext',
    'PrimitiveUnitScale',
    'REGISTERED_FILTER_PRIMITIVES',
    'RESVG_SUPPORTED_PRIMITIVES',
    'RGBA',
    'Rasterizer',
    'RenderContext',
    'Surface',
    'TessellationResult',
    'Tessellator',
    'UNSUPPORTED_FILTER_PRIMITIVES',
    'UnsupportedPrimitiveError',
    'Viewport',
    'apply_clip',
    'apply_filter',
    'apply_mask',
    'compute_marker_positions',
    'ensure_surface',
    'node_geometry',
    'plan_filter',
    'rasterize_clip_path',
    'rasterize_mask',
    'render',
    'resolve_clip_path',
    'resolve_marker',
    'resolve_mask',
    'filters',
    'geometry',
    'markers',
    'mask_clip',
    'pipeline',
    'rasterizer',
    'shapes',
    'surface'
]

# map symbol -> relative module
_symbol_map = {'ComponentTransferPlan': 'filters', 'FilterPlan': 'filters', 'plan_filter': 'filters', 'apply_filter': 'filters', 'UNSUPPORTED_FILTER_PRIMITIVES': 'filters', 'UnsupportedPrimitiveError': 'filters', 'RESVG_SUPPORTED_PRIMITIVES': 'filters', 'PrimitiveUnitScale': 'filters', 'FilterPrimitivePlan': 'filters', 'ComponentTransferFunction': 'filters', 'REGISTERED_FILTER_PRIMITIVES': 'filters', 'Tessellator': 'geometry', 'TessellationResult': 'geometry', 'compute_marker_positions': 'markers', 'resolve_marker': 'markers', 'MarkerPlacement': 'markers', 'ClipPathContext': 'mask_clip', 'resolve_clip_path': 'mask_clip', 'apply_clip': 'mask_clip', 'apply_mask': 'mask_clip', 'rasterize_clip_path': 'mask_clip', 'MaskContext': 'mask_clip', 'rasterize_mask': 'mask_clip', 'resolve_mask': 'mask_clip', 'RenderContext': 'pipeline', 'render': 'pipeline', 'Rasterizer': 'rasterizer', 'Viewport': 'rasterizer', 'node_geometry': 'shapes', 'Surface': 'surface', 'ensure_surface': 'surface', 'RGBA': 'surface'}
_module_map = {'filters': 'filters', 'geometry': 'geometry', 'markers': 'markers', 'mask_clip': 'mask_clip', 'pipeline': 'pipeline', 'rasterizer': 'rasterizer', 'shapes': 'shapes', 'surface': 'surface'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
