# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'FilterPlan',
    'GradientStop',
    'LinearGradient',
    'NormalizedNode',
    'NormalizedSvgTree',
    'PatternPaint',
    'RadialGradient',
    'Rasterizer',
    'RenderContext',
    'SolidPaint',
    'StrokePaint',
    'Surface',
    'TessellationResult',
    'Tessellator',
    'Viewport',
    'apply_filter',
    'compute_paints',
    'export_mask_png',
    'normalize_svg',
    'plan_filter',
    'rasterize_clip',
    'rasterize_mask',
    'render',
    'filters',
    'geometry',
    'mask_clip',
    'normalize',
    'paint',
    'pipeline',
    'rasterizer',
    'surface'
]

# map symbol -> relative module
_symbol_map = {'FilterPlan': 'filters', 'plan_filter': 'filters', 'apply_filter': 'filters', 'Tessellator': 'geometry', 'TessellationResult': 'geometry', 'rasterize_mask': 'mask_clip', 'rasterize_clip': 'mask_clip', 'export_mask_png': 'mask_clip', 'NormalizedNode': 'normalize', 'normalize_svg': 'normalize', 'NormalizedSvgTree': 'normalize', 'LinearGradient': 'paint', 'compute_paints': 'paint', 'GradientStop': 'paint', 'PatternPaint': 'paint', 'SolidPaint': 'paint', 'StrokePaint': 'paint', 'RadialGradient': 'paint', 'RenderContext': 'pipeline', 'render': 'pipeline', 'Viewport': 'rasterizer', 'Rasterizer': 'rasterizer', 'Surface': 'surface'}
_module_map = {'filters': 'filters', 'geometry': 'geometry', 'mask_clip': 'mask_clip', 'normalize': 'normalize', 'paint': 'paint', 'pipeline': 'pipeline', 'rasterizer': 'rasterizer', 'surface': 'surface'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
