# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'GroupMapper',
    'ImageDecision',
    'ImageMapper',
    'ImageProcessingAdapter',
    'ImageProcessingResult',
    'Mapper',
    'MapperError',
    'MapperResult',
    'OutputFormat',
    'PathDecision',
    'PathMapper',
    'TextMapper',
    'clip_result_to_xml',
    'create_image_adapter',
    'validate_mapper_result',
    'base',
    'clip_render',
    'group_mapper',
    'image_adapter',
    'image_mapper',
    'path_mapper',
    'text_mapper'
]

# map symbol -> relative module
_symbol_map = {'validate_mapper_result': 'base', 'OutputFormat': 'base', 'Mapper': 'base', 'MapperResult': 'base', 'MapperError': 'base', 'clip_result_to_xml': 'clip_render', 'GroupMapper': 'group_mapper', 'ImageProcessingAdapter': 'image_adapter', 'create_image_adapter': 'image_adapter', 'ImageProcessingResult': 'image_adapter', 'ImageDecision': 'image_mapper', 'ImageMapper': 'image_mapper', 'PathMapper': 'path_mapper', 'PathDecision': 'path_mapper', 'TextMapper': 'text_mapper'}
_module_map = {'base': 'base', 'clip_render': 'clip_render', 'group_mapper': 'group_mapper', 'image_adapter': 'image_adapter', 'image_mapper': 'image_mapper', 'path_mapper': 'path_mapper', 'text_mapper': 'text_mapper'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
