# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'AnimationHandler',
    'ColorAnimationHandler',
    'MotionAnimationHandler',
    'NumericAnimationHandler',
    'OpacityAnimationHandler',
    'SetAnimationHandler',
    'TransformAnimationHandler',
    'base',
    'color',
    'motion',
    'numeric',
    'opacity',
    'set',
    'transform'
]

# map symbol -> relative module
_symbol_map = {'AnimationHandler': 'base', 'ColorAnimationHandler': 'color', 'MotionAnimationHandler': 'motion', 'NumericAnimationHandler': 'numeric', 'OpacityAnimationHandler': 'opacity', 'SetAnimationHandler': 'set', 'TransformAnimationHandler': 'transform'}
_module_map = {'base': 'base', 'color': 'color', 'motion': 'motion', 'numeric': 'numeric', 'opacity': 'opacity', 'set': 'set', 'transform': 'transform'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
