# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ALLOWED_SLIDE_SIZE_MODES',
    'ASSETS_ROOT',
    'CONTENT_NS',
    'FONT_STYLE_ORDER',
    'FONT_STYLE_TAGS',
    'MASK_REL_TYPE',
    'PPTXPackageBuilder',
    'P_NS',
    'PackageWriter',
    'PackagingContext',
    'REL_NS',
    'R_DOC_NS',
    'SlideAssembler',
    'SlideAssembly',
    'StreamingPackageWriter',
    'THEME_FAMILY_NS',
    'THEME_NS',
    'content_type_for_extension',
    'normalize_style_kind',
    'read_svg_shapes',
    'safe_int',
    'write_pptx',
    'api',
    'emf',
    'pptx_assembly',
    'pptx_writer',
    'svg_reader'
]

# map symbol -> relative module
_symbol_map = {'REL_NS': 'pptx_assembly', 'content_type_for_extension': 'pptx_assembly', 'PackagingContext': 'pptx_assembly', 'PPTXPackageBuilder': 'pptx_assembly', 'SlideAssembly': 'pptx_assembly', 'FONT_STYLE_ORDER': 'pptx_assembly', 'THEME_NS': 'pptx_assembly', 'THEME_FAMILY_NS': 'pptx_assembly', 'ASSETS_ROOT': 'pptx_assembly', 'SlideAssembler': 'pptx_assembly', 'R_DOC_NS': 'pptx_assembly', 'safe_int': 'pptx_assembly', 'P_NS': 'pptx_assembly', 'FONT_STYLE_TAGS': 'pptx_assembly', 'CONTENT_NS': 'pptx_assembly', 'MASK_REL_TYPE': 'pptx_assembly', 'normalize_style_kind': 'pptx_assembly', 'ALLOWED_SLIDE_SIZE_MODES': 'pptx_assembly', 'write_pptx': 'pptx_assembly', 'PackageWriter': 'pptx_writer', 'StreamingPackageWriter': 'pptx_writer', 'read_svg_shapes': 'svg_reader'}
_module_map = {'api': 'api', 'emf': 'emf', 'pptx_assembly': 'pptx_assembly', 'pptx_writer': 'pptx_writer', 'svg_reader': 'svg_reader'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
