# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ALLOWED_SLIDE_SIZE_MODES',
    'ASSETS_ROOT',
    'CONTENT_NS',
    'MASK_REL_TYPE',
    'PPTXPackageBuilder',
    'P_NS',
    'REL_NS',
    'R_DOC_NS',
    'THEME_FAMILY_NS',
    'THEME_NS',
    'read_svg_shapes',
    'write_pptx',
    'api',
    'emf',
    'pptx_writer',
    'svg_reader'
]

# map symbol -> relative module
_symbol_map = {'MASK_REL_TYPE': 'pptx_writer', 'THEME_NS': 'pptx_writer', 'PPTXPackageBuilder': 'pptx_writer', 'ASSETS_ROOT': 'pptx_writer', 'THEME_FAMILY_NS': 'pptx_writer', 'write_pptx': 'pptx_writer', 'R_DOC_NS': 'pptx_writer', 'CONTENT_NS': 'pptx_writer', 'P_NS': 'pptx_writer', 'REL_NS': 'pptx_writer', 'ALLOWED_SLIDE_SIZE_MODES': 'pptx_writer', 'read_svg_shapes': 'svg_reader'}
_module_map = {'api': 'api', 'emf': 'emf', 'pptx_writer': 'pptx_writer', 'svg_reader': 'svg_reader'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
