# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'BlendFilter',
    'BlendParams',
    'CHANNELS',
    'ColorMatrixFilter',
    'ColorMatrixParams',
    'ComponentFunction',
    'ComponentTransferFilter',
    'CompositeFilter',
    'CompositeParams',
    'ConvolveMatrixFilter',
    'ConvolveMatrixParams',
    'DiffuseLightingFilter',
    'DisplacementMapFilter',
    'DropShadowFilter',
    'DropShadowParams',
    'FloodFilter',
    'FloodParams',
    'GaussianBlurFilter',
    'GaussianBlurParams',
    'GlowFilter',
    'ImageFilter',
    'ImageParams',
    'LightSource',
    'MergeFilter',
    'MergeParams',
    'MorphologyFilter',
    'MorphologyParams',
    'OffsetFilter',
    'OffsetParams',
    'SUPPORTED_MODES',
    'SUPPORTED_OPERATORS',
    'SpecularLightingFilter',
    'TileFilter',
    'TileParams',
    'TurbulenceFilter',
    'XLINK_HREF',
    'blend',
    'color_matrix',
    'component_transfer',
    'composite',
    'convolve_matrix',
    'displacement_map',
    'drop_shadow',
    'flood',
    'gaussian_blur',
    'image',
    'lighting',
    'merge',
    'morphology',
    'offset',
    'tile',
    'turbulence'
]

# map symbol -> relative module
_symbol_map = {'BlendFilter': 'blend', 'BlendParams': 'blend', 'SUPPORTED_MODES': 'blend', 'ColorMatrixParams': 'color_matrix', 'ColorMatrixFilter': 'color_matrix', 'ComponentTransferFilter': 'component_transfer', 'ComponentFunction': 'component_transfer', 'CHANNELS': 'component_transfer', 'CompositeParams': 'composite', 'SUPPORTED_OPERATORS': 'composite', 'CompositeFilter': 'composite', 'ConvolveMatrixParams': 'convolve_matrix', 'ConvolveMatrixFilter': 'convolve_matrix', 'DisplacementMapFilter': 'displacement_map', 'DropShadowParams': 'drop_shadow', 'DropShadowFilter': 'drop_shadow', 'GlowFilter': 'drop_shadow', 'FloodFilter': 'flood', 'FloodParams': 'flood', 'GaussianBlurParams': 'gaussian_blur', 'GaussianBlurFilter': 'gaussian_blur', 'ImageFilter': 'image', 'ImageParams': 'image', 'XLINK_HREF': 'image', 'LightSource': 'lighting', 'DiffuseLightingFilter': 'lighting', 'SpecularLightingFilter': 'lighting', 'MergeFilter': 'merge', 'MergeParams': 'merge', 'MorphologyFilter': 'morphology', 'MorphologyParams': 'morphology', 'OffsetFilter': 'offset', 'OffsetParams': 'offset', 'TileParams': 'tile', 'TileFilter': 'tile', 'TurbulenceFilter': 'turbulence'}
_module_map = {'blend': 'blend', 'color_matrix': 'color_matrix', 'component_transfer': 'component_transfer', 'composite': 'composite', 'convolve_matrix': 'convolve_matrix', 'displacement_map': 'displacement_map', 'drop_shadow': 'drop_shadow', 'flood': 'flood', 'gaussian_blur': 'gaussian_blur', 'image': 'image', 'lighting': 'lighting', 'merge': 'merge', 'morphology': 'morphology', 'offset': 'offset', 'tile': 'tile', 'turbulence': 'turbulence'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
