# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ConversionContextBundle',
    'ConvertResult',
    'Converter',
    'FallbackVariant',
    'SplitPage',
    'SvgConversionError',
    'SvgPageResult',
    'SvgPageSource',
    'SvgToPptxExporter',
    'SvgToPptxMultiResult',
    'SvgToPptxResult',
    'build_conversion_context',
    'build_fidelity_tier_variants',
    'clone_policy_context',
    'derive_variants_from_trace',
    'expand_page_with_variants',
    'resolve_policy_context',
    'resolve_policy_engine',
    'split_svg_into_pages',
    'animation',
    'auth',
    'conversion_context',
    'converter',
    'hyperlinks',
    'ir',
    'masks',
    'multipage',
    'parser',
    'parser.batch',
    'parser.colors',
    'parser.preprocess',
    'parser.split',
    'pipeline',
    'pipeline.mappers',
    'pptx_exporter',
    'resvg',
    'resvg.geometry',
    'resvg.painting',
    'resvg.parser',
    'resvg.text',
    'resvg.utils',
    'slide_orchestrator',
    'styling',
    'tracing',
    'traversal',
    'traversal.bridges'
]

# map symbol -> relative module
_symbol_map = {'ConversionContextBundle': 'conversion_context', 'clone_policy_context': 'conversion_context', 'build_conversion_context': 'conversion_context', 'resolve_policy_engine': 'conversion_context', 'resolve_policy_context': 'conversion_context', 'Converter': 'converter', 'ConvertResult': 'converter', 'SplitPage': 'multipage', 'split_svg_into_pages': 'multipage', 'SvgConversionError': 'pptx_exporter', 'SvgToPptxMultiResult': 'pptx_exporter', 'SvgPageResult': 'pptx_exporter', 'SvgPageSource': 'pptx_exporter', 'SvgToPptxExporter': 'pptx_exporter', 'SvgToPptxResult': 'pptx_exporter', 'expand_page_with_variants': 'slide_orchestrator', 'FallbackVariant': 'slide_orchestrator', 'derive_variants_from_trace': 'slide_orchestrator', 'build_fidelity_tier_variants': 'slide_orchestrator'}
_module_map = {'animation': 'animation', 'auth': 'auth', 'conversion_context': 'conversion_context', 'converter': 'converter', 'hyperlinks': 'hyperlinks', 'ir': 'ir', 'masks': 'masks', 'multipage': 'multipage', 'parser': 'parser', 'parser.batch': 'parser.batch', 'parser.colors': 'parser.colors', 'parser.preprocess': 'parser.preprocess', 'parser.split': 'parser.split', 'pipeline': 'pipeline', 'pipeline.mappers': 'pipeline.mappers', 'pptx_exporter': 'pptx_exporter', 'resvg': 'resvg', 'resvg.geometry': 'resvg.geometry', 'resvg.painting': 'resvg.painting', 'resvg.parser': 'resvg.parser', 'resvg.text': 'resvg.text', 'resvg.utils': 'resvg.utils', 'slide_orchestrator': 'slide_orchestrator', 'styling': 'styling', 'tracing': 'tracing', 'traversal': 'traversal', 'traversal.bridges': 'traversal.bridges'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
