# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ImageHrefResolver',
    'ImageRendering',
    'Options',
    'PRESENTATION_KEYS',
    'Presentation',
    'ShapeRendering',
    'Size',
    'StyleRule',
    'SvgDocument',
    'SvgNode',
    'TextRendering',
    'TransformCommand',
    'build_default_options',
    'collect_presentation',
    'convert_document',
    'parse_inline_style',
    'parse_stylesheet',
    'parse_svg_bytes',
    'parse_svg_file',
    'parse_svg_string',
    'parse_transform',
    'converter',
    'css',
    'options',
    'presentation',
    'style',
    'tree',
    'xml_loader'
]

# map symbol -> relative module
_symbol_map = {'convert_document': 'converter', 'parse_stylesheet': 'css', 'StyleRule': 'css', 'Size': 'options', 'Options': 'options', 'ShapeRendering': 'options', 'build_default_options': 'options', 'ImageHrefResolver': 'options', 'TextRendering': 'options', 'ImageRendering': 'options', 'Presentation': 'presentation', 'parse_transform': 'presentation', 'PRESENTATION_KEYS': 'presentation', 'TransformCommand': 'presentation', 'collect_presentation': 'presentation', 'parse_inline_style': 'style', 'SvgDocument': 'tree', 'SvgNode': 'tree', 'parse_svg_string': 'xml_loader', 'parse_svg_file': 'xml_loader', 'parse_svg_bytes': 'xml_loader'}
_module_map = {'converter': 'converter', 'css': 'css', 'options': 'options', 'presentation': 'presentation', 'style': 'style', 'tree': 'tree', 'xml_loader': 'xml_loader'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
