# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ClipPathData',
    'ClipPathSegment',
    'EMU_PER_PX',
    'commands_to_clip_segments',
    'rect_to_emu',
    'tessellate_segments',
    'tessellation'
]

# map symbol -> relative module
_symbol_map = {'rect_to_emu': 'tessellation', 'ClipPathSegment': 'tessellation', 'tessellate_segments': 'tessellation', 'EMU_PER_PX': 'tessellation', 'ClipPathData': 'tessellation', 'commands_to_clip_segments': 'tessellation'}
_module_map = {'tessellation': 'tessellation'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
