# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'GradientAnalysis',
    'GradientComplexity',
    'GradientMetrics',
    'GradientOptimization',
    'GradientProcessor',
    'ImageAnalysis',
    'ImageDimensions',
    'ImageFormat',
    'ImageOptimization',
    'ImageProcessor',
    'PatternAnalysis',
    'PatternComplexity',
    'PatternGeometry',
    'PatternOptimization',
    'PatternProcessor',
    'PatternType',
    'create_gradient_processor',
    'create_image_processor',
    'create_pattern_processor',
    'gradient_processor',
    'image_processor',
    'pattern_processor'
]

# map symbol -> relative module
_symbol_map = {'GradientOptimization': 'gradient_processor', 'GradientProcessor': 'gradient_processor', 'GradientMetrics': 'gradient_processor', 'GradientAnalysis': 'gradient_processor', 'GradientComplexity': 'gradient_processor', 'create_gradient_processor': 'gradient_processor', 'ImageFormat': 'image_processor', 'ImageAnalysis': 'image_processor', 'ImageProcessor': 'image_processor', 'create_image_processor': 'image_processor', 'ImageDimensions': 'image_processor', 'ImageOptimization': 'image_processor', 'PatternAnalysis': 'pattern_processor', 'PatternType': 'pattern_processor', 'create_pattern_processor': 'pattern_processor', 'PatternComplexity': 'pattern_processor', 'PatternProcessor': 'pattern_processor', 'PatternOptimization': 'pattern_processor', 'PatternGeometry': 'pattern_processor'}
_module_map = {'gradient_processor': 'gradient_processor', 'image_processor': 'image_processor', 'pattern_processor': 'pattern_processor'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
