# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'decrypt_token',
    'encrypt_token',
    'generate_encryption_key',
    'get_firestore_client',
    'initialize_firebase',
    'verify_firebase_token',
    'verify_firebase_token_with_scopes',
    'verify_google_identity_token',
    'verify_id_token',
    'encryption',
    'firebase',
    'middleware'
]

# map symbol -> relative module
_symbol_map = {'generate_encryption_key': 'encryption', 'encrypt_token': 'encryption', 'decrypt_token': 'encryption', 'initialize_firebase': 'firebase', 'verify_google_identity_token': 'firebase', 'verify_id_token': 'firebase', 'get_firestore_client': 'firebase', 'verify_firebase_token': 'middleware', 'verify_firebase_token_with_scopes': 'middleware'}
_module_map = {'encryption': 'encryption', 'firebase': 'firebase', 'middleware': 'middleware'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
