# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ClipComputeResult',
    'ClipCustGeom',
    'ClipFallback',
    'ClipMediaMeta',
    'CoordinateSpace',
    'ElementTraversal',
    'MarkerDefinition',
    'MarkerInstance',
    'MarkerTransform',
    'PreserveAspectRatio',
    'TransformParser',
    'TraversalHooksMixin',
    'ViewBox',
    'ViewBoxResult',
    'Viewport',
    'ViewportEngine',
    'apply_local_transform',
    'apply_marker_metadata',
    'build_marker_shapes',
    'build_marker_transform',
    'compute_clip_geometry',
    'compute_viewbox',
    'extract_url_id',
    'flatten_points',
    'generate_clip_geometry',
    'is_axis_aligned',
    'local_name',
    'navigation_from_attributes',
    'parse_marker_definition',
    'parse_preserve_aspect_ratio',
    'parse_viewbox_attribute',
    'process_anchor',
    'process_generic',
    'process_group',
    'process_use',
    'push_element_transform',
    'resolve_active_navigation',
    'resolve_clip_ref',
    'resolve_mask_ref',
    'resolve_viewbox',
    'resolve_viewbox_dimensions',
    'scaled_corner_radius',
    'transform_axis_aligned_rect',
    'viewbox_matrix_from_element',
    'bridges',
    'clip_geometry',
    'clipping',
    'constants',
    'coordinate_space',
    'geometry_utils',
    'hooks',
    'marker_runtime',
    'markers',
    'runtime',
    'transform_parser',
    'traversal',
    'viewbox'
]

# map symbol -> relative module
_symbol_map = {'ClipComputeResult': 'clip_geometry', 'ClipCustGeom': 'clip_geometry', 'compute_clip_geometry': 'clip_geometry', 'ClipMediaMeta': 'clip_geometry', 'ClipFallback': 'clip_geometry', 'resolve_clip_ref': 'clipping', 'resolve_mask_ref': 'clipping', 'generate_clip_geometry': 'clipping', 'extract_url_id': 'clipping', 'CoordinateSpace': 'coordinate_space', 'is_axis_aligned': 'geometry_utils', 'transform_axis_aligned_rect': 'geometry_utils', 'scaled_corner_radius': 'geometry_utils', 'TraversalHooksMixin': 'hooks', 'apply_marker_metadata': 'marker_runtime', 'build_marker_shapes': 'marker_runtime', 'apply_local_transform': 'markers', 'parse_marker_definition': 'markers', 'MarkerTransform': 'markers', 'MarkerDefinition': 'markers', 'MarkerInstance': 'markers', 'build_marker_transform': 'markers', 'flatten_points': 'markers', 'process_group': 'runtime', 'push_element_transform': 'runtime', 'resolve_active_navigation': 'runtime', 'local_name': 'runtime', 'process_generic': 'runtime', 'process_anchor': 'runtime', 'process_use': 'runtime', 'TransformParser': 'transform_parser', 'navigation_from_attributes': 'traversal', 'ElementTraversal': 'traversal', 'parse_preserve_aspect_ratio': 'viewbox', 'ViewportEngine': 'viewbox', 'resolve_viewbox': 'viewbox', 'ViewBox': 'viewbox', 'compute_viewbox': 'viewbox', 'Viewport': 'viewbox', 'parse_viewbox_attribute': 'viewbox', 'resolve_viewbox_dimensions': 'viewbox', 'ViewBoxResult': 'viewbox', 'PreserveAspectRatio': 'viewbox', 'viewbox_matrix_from_element': 'viewbox'}
_module_map = {'bridges': 'bridges', 'clip_geometry': 'clip_geometry', 'clipping': 'clipping', 'constants': 'constants', 'coordinate_space': 'coordinate_space', 'geometry_utils': 'geometry_utils', 'hooks': 'hooks', 'marker_runtime': 'marker_runtime', 'markers': 'markers', 'runtime': 'runtime', 'transform_parser': 'transform_parser', 'traversal': 'traversal', 'viewbox': 'viewbox'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
