# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'FREE_TIER_LIMIT',
    'create_checkout',
    'create_portal',
    'get_stripe_service',
    'get_subscription_repo',
    'get_subscription_status',
    'get_tier_from_price_id',
    'get_webhook_db',
    'handle_payment_failed',
    'handle_payment_succeeded',
    'handle_subscription_created',
    'handle_subscription_deleted',
    'handle_subscription_updated',
    'register_svg_routes',
    'router',
    'stripe_webhook',
    'export',
    'subscription',
    'svg',
    'tasks',
    'webhooks'
]

# map symbol -> relative module
_symbol_map = {'router': 'export', 'get_subscription_repo': 'subscription', 'create_checkout': 'subscription', 'FREE_TIER_LIMIT': 'subscription', 'create_portal': 'subscription', 'get_subscription_status': 'subscription', 'get_tier_from_price_id': 'subscription', 'get_stripe_service': 'subscription', 'register_svg_routes': 'svg', 'get_webhook_db': 'webhooks', 'handle_payment_failed': 'webhooks', 'stripe_webhook': 'webhooks', 'handle_subscription_deleted': 'webhooks', 'handle_payment_succeeded': 'webhooks', 'handle_subscription_updated': 'webhooks', 'handle_subscription_created': 'webhooks'}
_module_map = {'export': 'export', 'subscription': 'subscription', 'svg': 'svg', 'tasks': 'tasks', 'webhooks': 'webhooks'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
