# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'AuthKeyResponse',
    'ExchangePayload',
    'FREE_TIER_LIMIT',
    'GOOGLE_CLIENT_ID',
    'GOOGLE_CLIENT_SECRET',
    'REDIRECT_URI',
    'TaskRequest',
    'create_auth_key',
    'create_checkout',
    'create_export_job',
    'create_portal',
    'delete_job',
    'exchange_tokens',
    'get_job_status',
    'get_stripe_service',
    'get_subscription_repo',
    'get_subscription_status',
    'get_tier_from_price_id',
    'get_webhook_db',
    'handle_payment_failed',
    'handle_payment_succeeded',
    'handle_subscription_created',
    'handle_subscription_deleted',
    'handle_subscription_updated',
    'process_export_task',
    'register_svg_routes',
    'revoke_oauth',
    'stripe_webhook',
    'export',
    'oauth',
    'subscription',
    'svg',
    'tasks',
    'webhooks'
]

# map symbol -> relative module
_symbol_map = {'get_job_status': 'export', 'get_subscription_repo': 'export', 'FREE_TIER_LIMIT': 'export', 'delete_job': 'export', 'create_export_job': 'export', 'GOOGLE_CLIENT_SECRET': 'oauth', 'exchange_tokens': 'oauth', 'REDIRECT_URI': 'oauth', 'GOOGLE_CLIENT_ID': 'oauth', 'AuthKeyResponse': 'oauth', 'create_auth_key': 'oauth', 'ExchangePayload': 'oauth', 'revoke_oauth': 'oauth', 'create_portal': 'subscription', 'get_stripe_service': 'subscription', 'get_subscription_status': 'subscription', 'get_tier_from_price_id': 'subscription', 'create_checkout': 'subscription', 'register_svg_routes': 'svg', 'TaskRequest': 'tasks', 'process_export_task': 'tasks', 'stripe_webhook': 'webhooks', 'handle_subscription_updated': 'webhooks', 'handle_subscription_deleted': 'webhooks', 'handle_payment_succeeded': 'webhooks', 'handle_subscription_created': 'webhooks', 'get_webhook_db': 'webhooks', 'handle_payment_failed': 'webhooks'}
_module_map = {'export': 'export', 'oauth': 'oauth', 'subscription': 'subscription', 'svg': 'svg', 'tasks': 'tasks', 'webhooks': 'webhooks'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
