# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'Color',
    'FillStyle',
    'GradientStop',
    'LinearGradient',
    'PaintReference',
    'PatternPaint',
    'RadialGradient',
    'StrokeStyle',
    'TextStyle',
    'parse_color',
    'parse_rgb',
    'resolve_fill',
    'resolve_stroke',
    'resolve_text_style',
    'colors',
    'gradients',
    'paint'
]

# map symbol -> relative module
_symbol_map = {'parse_rgb': 'colors', 'RadialGradient': 'gradients', 'PatternPaint': 'gradients', 'GradientStop': 'gradients', 'LinearGradient': 'gradients', 'resolve_stroke': 'paint', 'parse_color': 'paint', 'TextStyle': 'paint', 'PaintReference': 'paint', 'resolve_fill': 'paint', 'FillStyle': 'paint', 'StrokeStyle': 'paint', 'resolve_text_style': 'paint', 'Color': 'paint'}
_module_map = {'colors': 'colors', 'gradients': 'gradients', 'paint': 'paint'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
