# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'EXTERNAL_PROTOCOLS',
    'NormalizationSettings',
    'ParseResult',
    'ParserConfig',
    'ParserOptions',
    'ParserReferences',
    'SVGParser',
    'SafeSVGNormalizer',
    'StyleContext',
    'XMLParser',
    'XML_DECLARATION',
    'build_style_context',
    'collect_namespaces',
    'collect_references',
    'compute_statistics',
    'fix_encoding_issues',
    'has_external_references',
    'load_dom',
    'prepare_svg_content',
    'resolve_viewport',
    'batch',
    'colors',
    'content_cleaner',
    'core',
    'dom_loader',
    'geometry',
    'normalization',
    'preprocess',
    'reference_collector',
    'references',
    'result',
    'split',
    'statistics',
    'style_context',
    'svg_parser',
    'units',
    'validators',
    'xml'
]

# map symbol -> relative module
_symbol_map = {'XML_DECLARATION': 'content_cleaner', 'fix_encoding_issues': 'content_cleaner', 'prepare_svg_content': 'content_cleaner', 'XMLParser': 'dom_loader', 'ParserOptions': 'dom_loader', 'load_dom': 'dom_loader', 'NormalizationSettings': 'normalization', 'SafeSVGNormalizer': 'normalization', 'collect_references': 'reference_collector', 'ParserReferences': 'reference_collector', 'EXTERNAL_PROTOCOLS': 'references', 'collect_namespaces': 'references', 'has_external_references': 'references', 'ParseResult': 'result', 'compute_statistics': 'statistics', 'build_style_context': 'style_context', 'resolve_viewport': 'style_context', 'StyleContext': 'style_context', 'ParserConfig': 'svg_parser', 'SVGParser': 'svg_parser'}
_module_map = {'batch': 'batch', 'colors': 'colors', 'content_cleaner': 'content_cleaner', 'core': 'core', 'dom_loader': 'dom_loader', 'geometry': 'geometry', 'normalization': 'normalization', 'preprocess': 'preprocess', 'reference_collector': 'reference_collector', 'references': 'references', 'result': 'result', 'split': 'split', 'statistics': 'statistics', 'style_context': 'style_context', 'svg_parser': 'svg_parser', 'units': 'units', 'validators': 'validators', 'xml': 'xml'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
