# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'FontResolver',
    'build_text_layout',
    'default_font_resolver',
    'fonts',
    'layout'
]

# map symbol -> relative module
_symbol_map = {'default_font_resolver': 'fonts', 'FontResolver': 'fonts', 'build_text_layout': 'layout'}
_module_map = {'fonts': 'fonts', 'layout': 'layout'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
