# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'DRAWINGML_HUNDREDTHS_PER_POINT',
    'DrawingMLTextGenerator',
    'FontResolver',
    'LayoutAnalysisResult',
    'TextLayoutAnalyzer',
    'TextLayoutComplexity',
    'TextRenderCoordinator',
    'TextRenderResult',
    'build_text_layout',
    'default_font_resolver',
    'drawingml_generator',
    'fonts',
    'layout',
    'layout_analyzer',
    'text_coordinator'
]

# map symbol -> relative module
_symbol_map = {'DRAWINGML_HUNDREDTHS_PER_POINT': 'drawingml_generator', 'DrawingMLTextGenerator': 'drawingml_generator', 'FontResolver': 'fonts', 'default_font_resolver': 'fonts', 'build_text_layout': 'layout', 'TextLayoutComplexity': 'layout_analyzer', 'TextLayoutAnalyzer': 'layout_analyzer', 'LayoutAnalysisResult': 'layout_analyzer', 'TextRenderCoordinator': 'text_coordinator', 'TextRenderResult': 'text_coordinator'}
_module_map = {'drawingml_generator': 'drawingml_generator', 'fonts': 'fonts', 'layout': 'layout', 'layout_analyzer': 'layout_analyzer', 'text_coordinator': 'text_coordinator'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
