#!/bin/bash

# Script to configure Firebase OAuth credentials for Google Slides publishing
set -e

PROJECT_ID="powerful-layout-467812-p1"

echo "🔧 Configuring Firebase OAuth Credentials for Slides Publishing"
echo ""
echo "To enable Google Slides publishing with refresh token support, you need to:"
echo ""
echo "1. Get the Firebase Web Client ID and Secret"
echo "2. Store them as environment variables in Cloud Run"
echo ""

# Open the Google Cloud Console to the Credentials page
echo "Opening Google Cloud Console Credentials page..."
open "https://console.cloud.google.com/apis/credentials?project=${PROJECT_ID}"

echo ""
echo "📋 Steps to find your credentials:"
echo ""
echo "1. Look for an OAuth 2.0 Client ID named 'Web client (auto created by Google Service)'"
echo "   or similar (this was auto-created when you enabled Google Sign-In in Firebase)"
echo ""
echo "2. Click on the client ID to view details"
echo ""
echo "3. Copy the 'Client ID' (looks like: xxxxx.apps.googleusercontent.com)"
echo ""
echo "4. Copy the 'Client secret' (looks like: GOCSPX-xxxxx)"
echo ""
echo "5. Run the following commands to store them as secrets:"
echo ""
echo "   # Store the client ID as a secret"
echo "   echo -n 'YOUR_CLIENT_ID' | gcloud secrets create firebase-web-client-id \\"
echo "     --data-file=- \\"
echo "     --replication-policy=automatic \\"
echo "     --project=${PROJECT_ID}"
echo ""
echo "   # Store the client secret"
echo "   echo -n 'YOUR_CLIENT_SECRET' | gcloud secrets create firebase-web-client-secret \\"
echo "     --data-file=- \\"
echo "     --replication-policy=automatic \\"
echo "     --project=${PROJECT_ID}"
echo ""
echo "6. Update the Cloud Run service to use these secrets:"
echo ""
echo "   gcloud run services update svg2ooxml-export \\"
echo "     --region=europe-west1 \\"
echo "     --update-secrets=FIREBASE_WEB_CLIENT_ID=firebase-web-client-id:latest \\"
echo "     --update-secrets=FIREBASE_WEB_CLIENT_SECRET=firebase-web-client-secret:latest \\"
echo "     --project=${PROJECT_ID}"
echo ""
echo "7. Grant the Cloud Run service account access to the secrets:"
echo ""
echo "   # Get the service account"
echo "   SERVICE_ACCOUNT=\$(gcloud run services describe svg2ooxml-export \\"
echo "     --region=europe-west1 \\"
echo "     --format='value(spec.template.spec.serviceAccountName)' \\"
echo "     --project=${PROJECT_ID})"
echo ""
echo "   # Grant access to client ID secret"
echo "   gcloud secrets add-iam-policy-binding firebase-web-client-id \\"
echo "     --member=\"serviceAccount:\${SERVICE_ACCOUNT}\" \\"
echo "     --role=\"roles/secretmanager.secretAccessor\" \\"
echo "     --project=${PROJECT_ID}"
echo ""
echo "   # Grant access to client secret"
echo "   gcloud secrets add-iam-policy-binding firebase-web-client-secret \\"
echo "     --member=\"serviceAccount:\${SERVICE_ACCOUNT}\" \\"
echo "     --role=\"roles/secretmanager.secretAccessor\" \\"
echo "     --project=${PROJECT_ID}"
echo ""
echo "✅ After completing these steps, your Figma plugin will be able to publish to Google Slides!"
echo ""
