# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'CoordinateSpace',
    'DecomposedTransform',
    'compose_matrix',
    'decompose_matrix',
    'matrix',
    'parse_transform',
    'rotate',
    'scale',
    'skew_x',
    'skew_y',
    'translate',
    'decompose',
    'matrix',
    'parser',
    'space'
]

# map symbol -> relative module
_symbol_map = {'compose_matrix': 'decompose', 'decompose_matrix': 'decompose', 'DecomposedTransform': 'decompose', 'translate': 'matrix', 'scale': 'matrix', 'skew_x': 'matrix', 'matrix': 'matrix', 'skew_y': 'matrix', 'rotate': 'matrix', 'parse_transform': 'parser', 'CoordinateSpace': 'space'}
_module_map = {'decompose': 'decompose', 'matrix': 'matrix', 'parser': 'parser', 'space': 'space'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
