# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'DEFAULT_POLICY',
    'DEFAULT_PROVIDERS',
    'DecisionReason',
    'FALLBACK_BITMAP',
    'FALLBACK_EMF',
    'FALLBACK_NATIVE',
    'FALLBACK_RASTERIZE',
    'FontDecisionContext',
    'FontEmbeddingPolicy',
    'MultipagePolicy',
    'POLICY_PRESETS',
    'Policy',
    'PolicyContext',
    'PolicyEngine',
    'PolicyProvider',
    'PolicyTarget',
    'QUALITY_PRESETS',
    'TargetRegistry',
    'TextDecision',
    'TextFallbackPolicy',
    'TextLayoutPolicy',
    'TextPolicy',
    'TextPolicyDecision',
    'WordArtPolicy',
    'apply_geometry_policy',
    'build_policy_engine',
    'explode_fallback_families',
    'extract_multipage_policy',
    'geometry_fallback_for',
    'load_policy',
    'resolve_text_policy',
    'constants',
    'engine',
    'geometry',
    'multipage',
    'providers',
    'rules',
    'setup',
    'targets',
    'text_policy'
]

# map symbol -> relative module
_symbol_map = {'geometry_fallback_for': 'constants', 'FALLBACK_NATIVE': 'constants', 'FALLBACK_RASTERIZE': 'constants', 'FALLBACK_EMF': 'constants', 'FALLBACK_BITMAP': 'constants', 'PolicyEngine': 'engine', 'PolicyContext': 'engine', 'PolicyProvider': 'engine', 'apply_geometry_policy': 'geometry', 'MultipagePolicy': 'multipage', 'extract_multipage_policy': 'multipage', 'POLICY_PRESETS': 'rules', 'load_policy': 'rules', 'DEFAULT_POLICY': 'rules', 'Policy': 'rules', 'DEFAULT_PROVIDERS': 'setup', 'build_policy_engine': 'setup', 'PolicyTarget': 'targets', 'TargetRegistry': 'targets', 'TextPolicyDecision': 'text_policy', 'FontDecisionContext': 'text_policy', 'TextDecision': 'text_policy', 'FontEmbeddingPolicy': 'text_policy', 'WordArtPolicy': 'text_policy', 'resolve_text_policy': 'text_policy', 'QUALITY_PRESETS': 'text_policy', 'TextFallbackPolicy': 'text_policy', 'TextLayoutPolicy': 'text_policy', 'DecisionReason': 'text_policy', 'explode_fallback_families': 'text_policy', 'TextPolicy': 'text_policy'}
_module_map = {'constants': 'constants', 'engine': 'engine', 'geometry': 'geometry', 'multipage': 'multipage', 'providers': 'providers', 'rules': 'rules', 'setup': 'setup', 'targets': 'targets', 'text_policy': 'text_policy'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
