# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'BlendMode',
    'Color',
    'ColorAccessibility',
    'ColorBatch',
    'ColorBlindnessType',
    'ColorHarmony',
    'ColorManipulation',
    'ColorParser',
    'ColorSpaceConverter',
    'ContrastLevel',
    'NAMED_COLORS',
    'color_to_hex',
    'get_css_color',
    'is_css_color',
    'oklab_to_oklch',
    'oklab_to_rgb',
    'oklch_to_oklab',
    'oklch_to_rgb',
    'rgb_to_oklab',
    'rgb_to_oklch',
    'accessibility',
    'batch',
    'color_spaces',
    'core',
    'css_colors',
    'harmony',
    'manipulation',
    'parser',
    'utils'
]

# map symbol -> relative module
_symbol_map = {'ColorAccessibility': 'accessibility', 'ContrastLevel': 'accessibility', 'ColorBlindnessType': 'accessibility', 'ColorBatch': 'batch', 'ColorSpaceConverter': 'color_spaces', 'oklch_to_oklab': 'color_spaces', 'oklch_to_rgb': 'color_spaces', 'rgb_to_oklch': 'color_spaces', 'rgb_to_oklab': 'color_spaces', 'oklab_to_rgb': 'color_spaces', 'oklab_to_oklch': 'color_spaces', 'Color': 'core', 'is_css_color': 'css_colors', 'NAMED_COLORS': 'css_colors', 'get_css_color': 'css_colors', 'ColorHarmony': 'harmony', 'BlendMode': 'manipulation', 'ColorManipulation': 'manipulation', 'ColorParser': 'parser', 'color_to_hex': 'utils'}
_module_map = {'accessibility': 'accessibility', 'batch': 'batch', 'color_spaces': 'color_spaces', 'core': 'core', 'css_colors': 'css_colors', 'harmony': 'harmony', 'manipulation': 'manipulation', 'parser': 'parser', 'utils': 'utils'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
