# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'PreserveAspectRatio',
    'ViewBox',
    'ViewBoxResult',
    'Viewport',
    'ViewportEngine',
    'compute_viewbox',
    'parse_preserve_aspect_ratio',
    'parse_viewbox_attribute',
    'resolve_viewbox',
    'resolve_viewbox_dimensions',
    'viewbox_matrix_from_element',
    'core',
    'strategies'
]

# map symbol -> relative module
_symbol_map = {'ViewBoxResult': 'core', 'PreserveAspectRatio': 'core', 'compute_viewbox': 'core', 'resolve_viewbox': 'core', 'ViewBox': 'core', 'resolve_viewbox_dimensions': 'core', 'Viewport': 'core', 'ViewportEngine': 'core', 'viewbox_matrix_from_element': 'core', 'parse_preserve_aspect_ratio': 'core', 'parse_viewbox_attribute': 'core'}
_module_map = {'core': 'core', 'strategies': 'strategies'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
