#!/usr/bin/env python3
"""
rebuild_inits.py
Reconstruct __init__.py files that were wiped, exporting public API lazily.

Usage:
  python rebuild_inits.py --root src/yourpkg [--dry-run]

What it does:
- Walks all packages under --root (dirs containing .py files).
- For each package dir, scans modules for top-level public symbols:
  * names in __all__ if present;
  * otherwise classes, functions, and UPPERCASE constants not starting with '_'.
- Writes/updates package __init__.py to export those names lazily via __getattr__ (PEP 562).
- Also exposes submodules and subpackages via explicit imports in __all__ for IDEs.
- Creates a backup of any existing __init__.py as __init__.py.bak if --overwrite is set.

Limitations:
- Won't modify namespace package semantics; if a package intentionally had no __init__.py, skip with --respect-namespace.
"""

import argparse
import ast
import sys
from pathlib import Path
from typing import Dict, List, Set, Tuple

SKIP_FILES = {"__init__.py", "__main__.py", "conftest.py"}
EXCLUDE_DIRS = {".git", ".venv", "venv", "build", "dist", "__pycache__", ".pytest_cache", ".mypy_cache", "tests"}


def is_package_dir(d: Path) -> bool:
    if not d.is_dir():
        return False
    if d.name in EXCLUDE_DIRS:
        return False
    # A "package dir" for our purpose contains at least one .py file (not just __init__.py)
    return any((p.suffix == ".py" and p.name not in SKIP_FILES) for p in d.iterdir() if p.is_file())


def scan_symbols(pyfile: Path) -> Tuple[Set[str], Set[str]]:
    """Return (explicit_all, inferred_public) for a module."""
    try:
        src = pyfile.read_text(encoding="utf-8")
    except Exception:
        return set(), set()
    try:
        tree = ast.parse(src, filename=str(pyfile))
    except SyntaxError:
        return set(), set()

    explicit_all: Set[str] = set()
    public: Set[str] = set()

    # Find __all__ assignment
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    try:
                        values: List[str] = []
                        if isinstance(node.value, (ast.List, ast.Tuple, ast.Set)):
                            for elt in node.value.elts:
                                if isinstance(elt, ast.Str):
                                    values.append(elt.s)
                                elif isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                                    values.append(elt.value)
                        explicit_all.update(values)
                    except Exception:
                        pass

    # If __all__ provided, we respect it. Otherwise infer.
    if not explicit_all:
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                name = node.name
                if not name.startswith("_"):
                    public.add(name)
            elif isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        name = target.id
                        if not name.startswith("_") and name.isupper():
                            public.add(name)

    return explicit_all, public


def rel_module_name(pkg_dir: Path, mod_path: Path) -> str:
    parts = list(mod_path.relative_to(pkg_dir).with_suffix("").parts)
    return ".".join(parts)


def build_pkg_export_map(pkg_dir: Path) -> Tuple[Dict[str, str], Set[str], Set[str]]:
    """Return (name->module map, submodules, subpackages) for a package directory."""
    name_to_module: Dict[str, str] = {}
    submodules: Set[str] = set()
    subpackages: Set[str] = set()

    for p in sorted(pkg_dir.rglob("*.py")):
        if any(x in EXCLUDE_DIRS for x in p.parts):
            continue
        if p.name == "__init__.py":
            if p.parent != pkg_dir:
                subpkg = ".".join(p.parent.relative_to(pkg_dir).parts)
                subpackages.add(subpkg)
            continue
        if p.name in SKIP_FILES:
            continue
        # Only immediate children and nested subpackages count as exports of the top-level package
        # We'll export names only from modules that are immediate children (e.g., pkg/module.py)
        if p.parent == pkg_dir:
            exp_all, inferred = scan_symbols(p)
            module_name = rel_module_name(pkg_dir, p)
            submodules.add(module_name)
            symbols = exp_all or inferred
            for sym in symbols:
                name_to_module.setdefault(sym, module_name)

    return name_to_module, submodules, subpackages


INIT_TEMPLATE = """\
# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
{all_list}
]

# map symbol -> relative module
_symbol_map = {symbol_map}
_module_map = {module_map}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{{mod}}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{{pkg}}", __name__)

    raise AttributeError(f"module {{__name__}} has no attribute {{name!r}}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
"""


def write_init(pkg_dir: Path, name_to_module: Dict[str, str], submodules: Set[str], subpackages: Set[str], dry_run: bool):
    # Build __all__: exported symbols + submodules + subpackages
    exported = sorted(name_to_module.keys())
    also = sorted(submodules | subpackages)
    all_items = exported + also

    all_list = ",\n".join(f"    {repr(x)}" for x in all_items)
    body = INIT_TEMPLATE.format(
        all_list=all_list,
        symbol_map=repr(name_to_module),
        module_map=repr({name: name for name in also}),
    )

    init_path = pkg_dir / "__init__.py"
    if dry_run:
        print(f"--- {init_path} (dry-run) ---\n{body}\n")
        return

    if init_path.exists():
        init_path.with_suffix(".py.bak").write_bytes(init_path.read_bytes())
    init_path.write_text(body, encoding="utf-8")
    print(f"Wrote {init_path.relative_to(Path.cwd())}  (exports: {len(name_to_module)} symbols, +{len(also)} modules/packages)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True, help="Root package directory (e.g., src/yourpkg)")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not root.exists() or not root.is_dir():
        print(f"--root {root} not found", file=sys.stderr)
        sys.exit(2)

    # Identify package dirs: any dir under root that has .py files
    pkgs = [root] + [d for d in root.rglob("*") if is_package_dir(d)]
    # Deduplicate while keeping parents before children
    seen: Set[Path] = set()
    ordered = []
    for d in sorted(pkgs, key=lambda p: (len(p.parts), str(p))):
        if d in seen:
            continue
        seen.add(d)
        ordered.append(d)

    for pkg_dir in ordered:
        name_to_module, submodules, subpackages = build_pkg_export_map(pkg_dir)
        # Only write __init__.py where it makes sense (top-level or true packages)
        if not name_to_module and not submodules and not subpackages and not (pkg_dir / "__init__.py").exists():
            # nothing to export and no prior __init__.py — skip
            continue
        write_init(pkg_dir, name_to_module, submodules, subpackages, args.dry_run)


if __name__ == "__main__":
    main()
