# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'CurveTextPositioner',
    'PathFeatures',
    'PathSamplingMethod',
    'PathSegment',
    'PathWarpFitter',
    'WarpFitResult',
    'WordArtClassificationResult',
    'classify_text_path_warp',
    'create_curve_text_positioner',
    'create_path_warp_fitter',
    'curve_text_positioning',
    'path_warp_fitter',
    'wordart_classifier'
]

# map symbol -> relative module
_symbol_map = {'PathWarpFitter': 'path_warp_fitter', 'CurveTextPositioner': 'curve_text_positioning', 'PathSegment': 'curve_text_positioning', 'WarpFitResult': 'path_warp_fitter', 'PathSamplingMethod': 'curve_text_positioning', 'create_path_warp_fitter': 'path_warp_fitter', 'create_curve_text_positioner': 'curve_text_positioning', 'WordArtClassificationResult': 'wordart_classifier', 'classify_text_path_warp': 'wordart_classifier', 'PathFeatures': 'wordart_classifier'}
_module_map = {'curve_text_positioning': 'curve_text_positioning', 'path_warp_fitter': 'path_warp_fitter', 'wordart_classifier': 'wordart_classifier'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
