# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'EMFPathAdapter',
    'EMFPathResult',
    'GradientStopDescriptor',
    'LinearGradientDescriptor',
    'MeshGradientDescriptor',
    'PathStyle',
    'PatternDescriptor',
    'RadialGradientDescriptor',
    'ResvgShapeAdapter',
    'ResvgShapeAdapterError',
    'TransformClass',
    'build_linear_gradient_element',
    'build_mesh_gradient_element',
    'build_pattern_element',
    'build_radial_gradient_element',
    'classify_linear',
    'decide_radial_policy',
    'describe_gradient_element',
    'describe_linear_gradient',
    'describe_pattern',
    'describe_pattern_element',
    'describe_radial_gradient',
    'linear_gradient_to_paint',
    'radial_gradient_to_paint',
    'emf_path_adapter',
    'resvg_gradient_adapter',
    'resvg_paint_bridge',
    'resvg_shape_adapter'
]

# map symbol -> relative module
_symbol_map = {'PathStyle': 'emf_path_adapter', 'EMFPathAdapter': 'emf_path_adapter', 'EMFPathResult': 'emf_path_adapter', 'radial_gradient_to_paint': 'resvg_gradient_adapter', 'decide_radial_policy': 'resvg_gradient_adapter', 'TransformClass': 'resvg_gradient_adapter', 'classify_linear': 'resvg_gradient_adapter', 'linear_gradient_to_paint': 'resvg_gradient_adapter', 'build_linear_gradient_element': 'resvg_paint_bridge', 'describe_gradient_element': 'resvg_paint_bridge', 'describe_pattern': 'resvg_paint_bridge', 'build_mesh_gradient_element': 'resvg_paint_bridge', 'PatternDescriptor': 'resvg_paint_bridge', 'describe_linear_gradient': 'resvg_paint_bridge', 'MeshGradientDescriptor': 'resvg_paint_bridge', 'LinearGradientDescriptor': 'resvg_paint_bridge', 'GradientStopDescriptor': 'resvg_paint_bridge', 'build_radial_gradient_element': 'resvg_paint_bridge', 'RadialGradientDescriptor': 'resvg_paint_bridge', 'describe_pattern_element': 'resvg_paint_bridge', 'build_pattern_element': 'resvg_paint_bridge', 'describe_radial_gradient': 'resvg_paint_bridge', 'ResvgShapeAdapter': 'resvg_shape_adapter', 'ResvgShapeAdapterError': 'resvg_shape_adapter'}
_module_map = {'emf_path_adapter': 'emf_path_adapter', 'resvg_gradient_adapter': 'resvg_gradient_adapter', 'resvg_paint_bridge': 'resvg_paint_bridge', 'resvg_shape_adapter': 'resvg_shape_adapter'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
