# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ClipDefinition',
    'ClipPathExtractor',
    'ElementTraversal',
    'FONT_WEIGHT_BOLD_THRESHOLD',
    'HyperlinkProcessor',
    'MAX_SIMPLE_PATH_SEGMENTS',
    'MIN_PATH_COORDS_FOR_ARC',
    'MIN_PATH_COORDS_FOR_CUBIC',
    'MIN_PATH_COORDS_FOR_CURVE',
    'MIN_PATH_COORDS_FOR_LINE',
    'SVGValidator',
    'StyleContextBuilder',
    'XMLParser',
    'clip_parser',
    'constants',
    'element_traversal',
    'hyperlink_processor',
    'style_context',
    'validator',
    'xml_parser'
]

# map symbol -> relative module
_symbol_map = {'ClipPathExtractor': 'clip_parser', 'ClipDefinition': 'clip_parser', 'MIN_PATH_COORDS_FOR_CUBIC': 'constants', 'MAX_SIMPLE_PATH_SEGMENTS': 'constants', 'MIN_PATH_COORDS_FOR_ARC': 'constants', 'MIN_PATH_COORDS_FOR_CURVE': 'constants', 'MIN_PATH_COORDS_FOR_LINE': 'constants', 'FONT_WEIGHT_BOLD_THRESHOLD': 'constants', 'ElementTraversal': 'element_traversal', 'HyperlinkProcessor': 'hyperlink_processor', 'StyleContextBuilder': 'style_context', 'SVGValidator': 'validator', 'XMLParser': 'xml_parser'}
_module_map = {'clip_parser': 'clip_parser', 'constants': 'constants', 'element_traversal': 'element_traversal', 'hyperlink_processor': 'hyperlink_processor', 'style_context': 'style_context', 'validator': 'validator', 'xml_parser': 'xml_parser'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
