# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'BrushSpec',
    'DashPattern',
    'EMFBlob',
    'EMFBrushStyle',
    'EMFHatchStyle',
    'EMFMedia',
    'EMFRecordType',
    'EMFRelationshipManager',
    'EMU_PER_INCH',
    'HMM_PER_EMU',
    'NULL_BRUSH_HANDLE',
    'NULL_PEN_HANDLE',
    'PenSpec',
    'apply_dash_pattern',
    'flatten_segments',
    'blob',
    'packager',
    'path'
]

# map symbol -> relative module
_symbol_map = {'BrushSpec': 'blob', 'PenSpec': 'blob', 'EMU_PER_INCH': 'blob', 'EMFHatchStyle': 'blob', 'EMFBlob': 'blob', 'EMFBrushStyle': 'blob', 'HMM_PER_EMU': 'blob', 'EMFRecordType': 'blob', 'NULL_BRUSH_HANDLE': 'blob', 'NULL_PEN_HANDLE': 'blob', 'EMFMedia': 'packager', 'EMFRelationshipManager': 'packager', 'apply_dash_pattern': 'path', 'flatten_segments': 'path', 'DashPattern': 'path'}
_module_map = {'blob': 'blob', 'packager': 'packager', 'path': 'path'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
