# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'DisplacementMapParameters',
    'TurbulenceParameters',
    'build_exporter_hook',
    'parse_channel',
    'parse_displacement_map',
    'parse_number',
    'parse_turbulence',
    'dml',
    'parsing'
]

# map symbol -> relative module
_symbol_map = {'build_exporter_hook': 'dml', 'TurbulenceParameters': 'parsing', 'parse_number': 'parsing', 'parse_turbulence': 'parsing', 'parse_channel': 'parsing', 'DisplacementMapParameters': 'parsing', 'parse_displacement_map': 'parsing'}
_module_map = {'dml': 'dml', 'parsing': 'parsing'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
