# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'ENV_FONT_DIRS',
    'EmbeddingPermission',
    'FontEmbeddingEngine',
    'FontEmbeddingRequest',
    'FontEmbeddingResult',
    'FontFetcher',
    'FontMatch',
    'FontOptimisationLevel',
    'FontProvider',
    'FontQuery',
    'FontService',
    'FontSource',
    'FontSystem',
    'FontSystemConfig',
    'MAX_FONT_SIZE',
    'collect_font_directories',
    'parse_directory_list',
    'embedding',
    'fetcher',
    'providers',
    'service',
    'system'
]

# map symbol -> relative module
_symbol_map = {'EmbeddingPermission': 'embedding', 'FontEmbeddingEngine': 'embedding', 'FontOptimisationLevel': 'embedding', 'FontEmbeddingResult': 'embedding', 'FontEmbeddingRequest': 'embedding', 'FontFetcher': 'fetcher', 'FontSource': 'fetcher', 'MAX_FONT_SIZE': 'fetcher', 'FontMatch': 'service', 'FontProvider': 'service', 'FontQuery': 'service', 'FontService': 'service', 'collect_font_directories': 'system', 'FontSystem': 'system', 'FontSystemConfig': 'system', 'parse_directory_list': 'system', 'ENV_FONT_DIRS': 'system'}
_module_map = {'embedding': 'embedding', 'fetcher': 'fetcher', 'providers': 'providers', 'service': 'service', 'system': 'system'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
